const fs = require('fs');

const translations = {
  "abject": "卑劣的 / 淒慘的",
  "aberration": "異常 / 偏差",
  "abjure": "發誓放棄 / 公開放棄",
  "abnegation": "拒絕 / 放棄",
  "abrogate": "廢除 / 取消",
  "abscond": "潛逃 / 逃跑",
  "abstruse": "深奧的 / 難懂的",
  "accede": "同意 / 答應",
  "accost": "搭訕 / 攀談",
  "accretion": "增加 / 累積",
  "acumen": "敏銳 / 聰明",
  "adamant": "堅決的 / 固執的",
  "admonish": "告誡 / 警告",
  "adumbrate": "預示 / 畫輪廓",
  "adverse": "不利的 / 敵對的",
  "advocate": "提倡者 / 擁護者",
  "affluent": "富裕的 / 豐富的",
  "aggrandize": "擴大 / 誇大",
  "alacrity": "敏捷 / 樂意",
  "alias": "別名 / 化名",
  "ambivalent": "矛盾的 / 猶豫不決的",
  "amenable": "順從的 / 願意接受的",
  "amorphous": "無定形的 / 雜亂的",
  "anachronistic": "時代錯誤的 / 過時的",
  "anathema": "詛咒 / 令人討厭的事物",
  "annex": "附加 / 併吞",
  "antediluvian": "史前的 / 陳舊的",
  "antiseptic": "抗菌的 / 防腐的",
  "apathetic": "冷漠的 / 無動於衷的",
  "antithesis": "對立面 / 對照",
  "apocryphal": "偽造的 / 可疑的",
  "approbation": "認可 / 贊許",
  "arbitrary": "任意的 / 專斷的",
  "arboreal": "樹木的 / 棲息在樹上的",
  "arcane": "神秘的 / 晦澀難懂的",
  "archetypal": "原型的 / 典型的",
  "arrogate": "冒稱 / 僭取",
  "ascetic": "苦行的 / 禁慾的",
  "aspersion": "誹謗 / 中傷",
  "assiduous": "勤奮的 / 專心致志的",
  "atrophy": "萎縮 / 退化",
  "bane": "禍根 / 苦惱之源",
  "bashful": "害羞的 / 羞怯的",
  "beguile": "欺騙 / 迷住",
  "bereft": "喪失的 / 失去的",
  "blandishment": "奉承 / 甜言蜜語",
  "bilk": "欺騙 / 詐騙",
  "bombastic": "誇大的 / 言過其實的",
  "cajole": "哄騙 / 誘騙",
  "callous": "冷酷無情的 / 麻木的",
  "calumny": "誹謗 / 誣衊",
  "camaraderie": "同志情誼 / 友情",
  "candor": "坦白 / 直率",
  "capitulate": "投降 / 屈服",
  "carouse": "狂歡 / 痛飲",
  "carp": "挑剔 / 吹毛求疵",
  "caucus": "核心會議 / 幹部會議",
  "cavort": "歡躍 / 嬉戲",
  "circumlocution": "迂迴的說法 / 累贅的陳述",
  "circumscribe": "限制 / 畫界線",
  "circumvent": "規避 / 繞過",
  "clamor": "喧鬧 / 叫嚷",
  "cleave": "劈開 / 緊貼",
  "cobbler": "鞋匠",
  "cogent": "有說服力的 / 令人信服的",
  "cognizant": "知道的 / 意識到的",
  "commensurate": "相稱的 / 相當的",
  "complement": "補充物 / 補足",
  "compunction": "內疚 / 悔恨",
  "concomitant": "伴隨的 / 同時發生的",
  "conduit": "導管 / 管道",
  "conflagration": "大火 / 戰火",
  "congruity": "一致 / 適合",
  "connive": "縱容 / 默許",
  "consign": "委託 / 交付",
  "constituent": "成分 / 選民",
  "construe": "解釋 / 理解為",
  "contusion": "挫傷 / 瘀傷",
  "contrite": "悔罪的 / 痛悔的",
  "contentious": "有爭議的 / 好爭吵的",
  "contravene": "違反 / 抵觸",
  "convivial": "歡樂的 / 友好的",
  "corpulence": "肥胖 / 臃腫",
  "covet": "貪求 / 覬覦",
  "cupidity": "貪婪 / 貪財",
  "dearth": "缺乏 / 稀少",
  "debacle": "慘敗 / 崩潰",
  "debauch": "墮落 / 放蕩",
  "debunk": "揭穿 / 暴露",
  "defunct": "死亡的 / 廢止的",
  "demagogue": "煽動者 / 蠱惑民心的政客",
  "denigrate": "貶低 / 詆毀",
  "derivative": "衍生物 / 派生的",
  "despot": "專制君主 / 暴君",
  "diaphanous": "透明的 / 精緻的",
  "didactic": "說教的 / 教誨的",
  "dirge": "輓歌 / 哀樂",
  "disaffected": "不滿的 / 叛逆的",
  "discomfit": "使窘迫 / 挫敗",
  "disparate": "不同的 / 異類的",
  "dispel": "驅散 / 消除",
  "disrepute": "聲名狼藉 / 壞名聲",
  "divisive": "引起分歧的 / 導致分裂的",
  "dogmatic": "教條的 / 武斷的",
  "dour": "嚴厲的 / 陰沉的",
  "duplicity": "口是心非 / 欺騙",
  "duress": "脅迫 / 壓力",
  "eclectic": "折衷的 / 綜合的",
  "edict": "法令 / 佈告",
  "ebullient": "熱情洋溢的 / 沸騰的",
  "egregious": "極壞的 / 令人震驚的",
  "elegy": "輓歌 / 哀歌",
  "elicit": "引出 / 探出",
  "embezzlement": "貪污 / 盜用",
  "emend": "校訂 / 修改",
  "emollient": "潤膚劑 / 緩和的",
  "empirical": "經驗主義的 / 實證的",
  "emulate": "效仿 / 模仿",
  "enervate": "使衰弱 / 使失去活力",
  "enfranchise": "給予選舉權 / 解放",
  "engender": "產生 / 引起",
  "ephemeral": "短暫的 / 朝生暮死的",
  "epistolary": "書信的 / 書信體的",
  "equanimity": "平靜 / 鎮定",
  "equivocal": "模稜兩可的 / 含糊的",
  "espouse": "支持 / 擁護",
  "evanescent": "逐漸消失的 / 短暫的",
  "evince": "表明 / 顯示",
  "exacerbate": "惡化 / 加劇",
  "exhort": "勸告 / 勉勵",
  "execrable": "劣等的 / 該咒罵的",
  "exigent": "緊急的 / 迫切的",
  "expedient": "權宜之計 / 有利的",
  "expiate": "贖罪 / 補償",
  "expunge": "刪除 / 抹去",
  "extraneous": "無關的 / 外來的",
  "extol": "讚美 / 頌揚",
  "extant": "現存的 / 尚存的",
  "expurgate": "刪除（不當內容） / 淨化",
  "fallacious": "謬誤的 / 騙人的",
  "fatuous": "愚笨的 / 昏庸的",
  "fetter": "束縛 / 腳鐐",
  "flagrant": "明目張膽的 / 惡名昭彰的",
  "foil": "阻撓 / 挫敗",
  "forbearance": "忍耐 / 寬容",
  "fortuitous": "偶然的 / 幸運的",
  "fractious": "易怒的 / 倔強的",
  "garrulous": "喋喋不休的 / 饒舌的",
  "gourmand": "貪吃者 / 饕客",
  "grandiloquent": "誇張的 / 浮誇的",
  "gratuitous": "無緣無故的 / 免費的",
  "hapless": "倒霉的 / 不幸的",
  "hegemony": "霸權 / 領導權",
  "heterogenous": "異類的 / 混合的",
  "iconoclast": "偶像破壞者 / 反傳統者",
  "idiosyncratic": "特質的 / 獨特的",
  "impecunious": "貧窮的 / 一文不名的",
  "impetuous": "衝動的 / 魯莽的",
  "impinge": "侵犯 / 撞擊",
  "impute": "歸咎於 / 歸因於",
  "inane": "空洞的 / 愚蠢的",
  "inchoate": "早期的 / 未成形的",
  "incontrovertible": "無可辯駁的 / 不容置疑的",
  "incumbent": "義不容辭的 / 現任的",
  "inexorable": "不可阻擋的 / 無情的",
  "inimical": "敵意的 / 有害的",
  "injunction": "命令 / 禁令",
  "inoculate": "接種 / 灌輸",
  "insidious": "潛伏的 / 陰險的",
  "instigate": "煽動 / 唆使",
  "insurgent": "叛亂者 / 起義者",
  "interlocutor": "對話者 / 談話對手",
  "intimation": "暗示 / 透露",
  "inure": "使習慣於 / 生效",
  "invective": "謾罵 / 惡言",
  "intransigent": "不妥協的 / 固執的",
  "inveterate": "根深蒂固的 / 積習的",
  "irreverence": "不敬 / 輕蔑",
  "knell": "喪鐘聲 / 凶兆",
  "laconic": "簡潔的 / 寡言的",
  "largesse": "慷慨 / 恩賜",
  "legerdemain": "戲法 / 騙術",
  "libertarian": "自由意志主義者 / 倡導自由的人",
  "licentious": "放蕩的 / 淫亂的",
  "linchpin": "關鍵人物 / 樞紐",
  "litigant": "訴訟當事人",
  "maelstrom": "大漩渦 / 大混亂",
  "maudlin": "傷感的 / 容易流淚的",
  "maverick": "特立獨行者 / 不守常規的人",
  "mawkish": "無病呻吟的 / 令人作嘔的",
  "maxim": "格言 / 箴言",
  "mendacious": "虛假的 / 說謊的",
  "modicum": "少量 / 一點點",
  "morass": "沼澤 / 困境",
  "mores": "風俗 / 習慣",
  "munificent": "慷慨的 / 豐厚的",
  "multifarious": "多種多樣的 / 各式各樣的",
  "nadir": "最低點 / 深淵",
  "negligent": "疏忽的 / 粗心的",
  "neophyte": "新手 / 初學者",
  "noisome": "惡臭的 / 有害的",
  "noxious": "有毒的 / 有害的",
  "obdurate": "頑固的 / 執拗的",
  "obfuscate": "使模糊 / 使困惑",
  "obstreperous": "喧鬧的 / 難駕馭的",
  "officious": "多管閒事的 / 愛發號施令的",
  "onerous": "繁重的 / 麻煩的",
  "ostensible": "表面的 / 假裝的",
  "ostracism": "排斥 / 放逐",
  "palliate": "減輕 / 掩飾",
  "panacea": "萬靈藥 / 解決所有問題的方法",
  "paradigm": "範例 / 模範",
  "pariah": "賤民 / 被社會遺棄者",
  "partisan": "黨派的 / 偏袒的",
  "paucity": "缺乏 / 稀少",
  "pejorative": "貶義的 / 輕蔑的",
  "pellucid": "清澈的 / 易懂的",
  "penchant": "傾向 / 嗜好",
  "penurious": "吝嗇的 / 貧窮的",
  "pert": "俏皮的 / 魯莽的",
  "pernicious": "有害的 / 致命的",
  "pertinacious": "頑固的 / 執拗的",
  "phlegmatic": "冷靜的 / 遲鈍的",
  "philanthropic": "慈善的 / 博愛的",
  "pithy": "簡練的 / 精闢的",
  "platitude": "老生常談 / 陳詞濫調",
  "plaudit": "喝采 / 讚賞",
  "plenitude": "豐富 / 充足",
  "plethora": "過剩 / 泛濫",
  "portent": "預兆 / 凶兆",
  "potentate": "統治者 / 君主",
  "preclude": "排除 / 阻止",
  "predilection": "偏好 / 嗜好",
  "preponderance": "優勢 / 多數",
  "presage": "預示 / 預兆",
  "probity": "誠實 / 正直",
  "proclivity": "傾向 / 癖性",
  "profligate": "揮霍的 / 墮落的",
  "promulgate": "公布 / 頒布",
  "proscribe": "禁止 / 放逐",
  "protean": "千變萬化的 / 多變的",
  "prurient": "好色的 / 淫慾的",
  "puerile": "幼稚的 / 孩童的",
  "pugnacious": "好鬥的 / 好戰的",
  "pulchritude": "美麗 / 標緻",
  "punctilious": "一絲不苟的 / 拘泥細節的",
  "quaint": "古雅的 / 奇特的",
  "quixotic": "不切實際的 / 唐吉訶德式的",
  "quandary": "困境 / 窘境",
  "recalcitrant": "桀驁不馴的 / 頑抗的",
  "redoubtable": "可怕的 / 令人敬畏的",
  "relegate": "降級 / 委託",
  "remiss": "怠忽職守的 / 疏忽的",
  "reprieve": "緩刑 / 暫緩",
  "reprobate": "墮落者 / 惡棍",
  "rescind": "廢除 / 取消",
  "requisition": "徵用 / 需求",
  "rife": "充斥的 / 普遍的",
  "sanctimonious": "假裝虔誠的 / 偽善的",
  "sanguine": "樂觀的 / 紅潤的",
  "scurrilous": "粗俗的 / 誹謗的",
  "semaphore": "臂板信號 / 信號標",
  "serendipity": "機緣巧合 / 意外發現",
  "sobriety": "清醒 / 莊重",
  "solicitous": "關切的 / 掛念的",
  "solipsism": "唯我論",
  "spurious": "偽造的 / 欺騙的",
  "staid": "沉著的 / 穩重的",
  "stolid": "遲鈍的 / 缺乏熱情的",
  "subjugate": "征服 / 降伏",
  "surfeit": "過量 / 飲食過度",
  "surreptitious": "秘密的 / 鬼鬼祟祟的",
  "swarthy": "黝黑的 / 黑皮膚的",
  "tangential": "離題的 / 膚淺的",
  "tome": "大部頭書 / 巨著",
  "toady": "諂媚者 / 拍馬屁的人",
  "torpid": "遲鈍的 / 懶散的",
  "travesty": "拙劣的模仿 / 嘲弄",
  "trenchant": "銳利的 / 一針見血的",
  "trite": "陳腐的 / 平庸的",
  "truculent": "好鬥的 / 殘暴的",
  "turpitude": "卑鄙 / 墮落",
  "ubiquitous": "無所不在的 / 普遍存在的",
  "umbrage": "生氣 / 怨恨",
  "upbraid": "責罵 / 訓斥",
  "utilitarian": "功利的 / 實用的",
  "veracity": "誠實 / 真實",
  "vestige": "遺跡 / 殘餘",
  "vicissitude": "變遷 / 盛衰",
  "vilify": "誹謗 / 貶低",
  "virtuoso": "藝術大師 / 名家",
  "vitriolic": "尖酸刻薄的 / 惡意的",
  "vituperate": "謾罵 / 責罵",
  "vociferous": "喧嘩的 / 大聲叫嚷的",
  "wanton": "肆無忌憚的 / 淫蕩的",
  "winsome": "迷人的 / 惹人喜愛的",
  "yoke": "結合 / 束縛",
  "zephyr": "微風 / 和風",
  "wily": "狡猾的 / 詭計多端的",
  "tirade": "長篇激烈的演說 / 抨擊"
};

const words = Object.keys(translations).map(word => {
  return {
    word: word,
    meaning: translations[word],
    pos: "n" 
  };
});

let output = `export interface Word {
  word: string;
  meaning: string;
  pos: string; // Part of speech
}

export const wordSets: Record<number, Word[]> = {
`;

let setNum = 1;
for (let i = 0; i < words.length; i += 20) {
  const chunk = words.slice(i, i + 20);
  output += `  ${setNum}: [\n`;
  chunk.forEach((w, idx) => {
    output += `    { word: "${w.word}", meaning: "${w.meaning}", pos: "${w.pos}" }${idx < chunk.length - 1 ? ',' : ''}\n`;
  });
  output += `  ]${i + 20 < words.length ? ',' : ''}\n`;
  setNum++;
}

output += `};

export function getWordSet(round: number): Word[] {
  // If we run out of sets, loop back
  const setKeys = Object.keys(wordSets).map(Number).sort((a, b) => a - b);
  const maxSet = setKeys[setKeys.length - 1];
  const actualRound = ((round - 1) % maxSet) + 1;
  return wordSets[actualRound];
}
`;

fs.writeFileSync('src/wordSets.ts', output);
console.log('Done translating wordSets.ts');
