export interface Word {
  word: string;
  meaning: string;
  pos: string; // Part of speech
}

export const wordSets: Record<number, Word[]> = {
  1: [
    { word: "abject", meaning: "卑劣的 / 淒慘的", pos: "n" },
    { word: "aberration", meaning: "異常 / 偏差", pos: "n" },
    { word: "abjure", meaning: "發誓放棄 / 公開放棄", pos: "n" },
    { word: "abnegation", meaning: "拒絕 / 放棄", pos: "n" },
    { word: "abrogate", meaning: "廢除 / 取消", pos: "n" },
    { word: "abscond", meaning: "潛逃 / 逃跑", pos: "n" },
    { word: "abstruse", meaning: "深奧的 / 難懂的", pos: "n" },
    { word: "accede", meaning: "同意 / 答應", pos: "n" },
    { word: "accost", meaning: "搭訕 / 攀談", pos: "n" },
    { word: "accretion", meaning: "增加 / 累積", pos: "n" },
    { word: "acumen", meaning: "敏銳 / 聰明", pos: "n" },
    { word: "adamant", meaning: "堅決的 / 固執的", pos: "n" },
    { word: "admonish", meaning: "告誡 / 警告", pos: "n" },
    { word: "adumbrate", meaning: "預示 / 畫輪廓", pos: "n" },
    { word: "adverse", meaning: "不利的 / 敵對的", pos: "n" },
    { word: "advocate", meaning: "提倡者 / 擁護者", pos: "n" },
    { word: "affluent", meaning: "富裕的 / 豐富的", pos: "n" },
    { word: "aggrandize", meaning: "擴大 / 誇大", pos: "n" },
    { word: "alacrity", meaning: "敏捷 / 樂意", pos: "n" },
    { word: "alias", meaning: "別名 / 化名", pos: "n" }
  ],
  2: [
    { word: "ambivalent", meaning: "矛盾的 / 猶豫不決的", pos: "n" },
    { word: "amenable", meaning: "順從的 / 願意接受的", pos: "n" },
    { word: "amorphous", meaning: "無定形的 / 雜亂的", pos: "n" },
    { word: "anachronistic", meaning: "時代錯誤的 / 過時的", pos: "n" },
    { word: "anathema", meaning: "詛咒 / 令人討厭的事物", pos: "n" },
    { word: "annex", meaning: "附加 / 併吞", pos: "n" },
    { word: "antediluvian", meaning: "史前的 / 陳舊的", pos: "n" },
    { word: "antiseptic", meaning: "抗菌的 / 防腐的", pos: "n" },
    { word: "apathetic", meaning: "冷漠的 / 無動於衷的", pos: "n" },
    { word: "antithesis", meaning: "對立面 / 對照", pos: "n" },
    { word: "apocryphal", meaning: "偽造的 / 可疑的", pos: "n" },
    { word: "approbation", meaning: "認可 / 贊許", pos: "n" },
    { word: "arbitrary", meaning: "任意的 / 專斷的", pos: "n" },
    { word: "arboreal", meaning: "樹木的 / 棲息在樹上的", pos: "n" },
    { word: "arcane", meaning: "神秘的 / 晦澀難懂的", pos: "n" },
    { word: "archetypal", meaning: "原型的 / 典型的", pos: "n" },
    { word: "arrogate", meaning: "冒稱 / 僭取", pos: "n" },
    { word: "ascetic", meaning: "苦行的 / 禁慾的", pos: "n" },
    { word: "aspersion", meaning: "誹謗 / 中傷", pos: "n" },
    { word: "assiduous", meaning: "勤奮的 / 專心致志的", pos: "n" }
  ],
  3: [
    { word: "atrophy", meaning: "萎縮 / 退化", pos: "n" },
    { word: "bane", meaning: "禍根 / 苦惱之源", pos: "n" },
    { word: "bashful", meaning: "害羞的 / 羞怯的", pos: "n" },
    { word: "beguile", meaning: "欺騙 / 迷住", pos: "n" },
    { word: "bereft", meaning: "喪失的 / 失去的", pos: "n" },
    { word: "blandishment", meaning: "奉承 / 甜言蜜語", pos: "n" },
    { word: "bilk", meaning: "欺騙 / 詐騙", pos: "n" },
    { word: "bombastic", meaning: "誇大的 / 言過其實的", pos: "n" },
    { word: "cajole", meaning: "哄騙 / 誘騙", pos: "n" },
    { word: "callous", meaning: "冷酷無情的 / 麻木的", pos: "n" },
    { word: "calumny", meaning: "誹謗 / 誣衊", pos: "n" },
    { word: "camaraderie", meaning: "同志情誼 / 友情", pos: "n" },
    { word: "candor", meaning: "坦白 / 直率", pos: "n" },
    { word: "capitulate", meaning: "投降 / 屈服", pos: "n" },
    { word: "carouse", meaning: "狂歡 / 痛飲", pos: "n" },
    { word: "carp", meaning: "挑剔 / 吹毛求疵", pos: "n" },
    { word: "caucus", meaning: "核心會議 / 幹部會議", pos: "n" },
    { word: "cavort", meaning: "歡躍 / 嬉戲", pos: "n" },
    { word: "circumlocution", meaning: "迂迴的說法 / 累贅的陳述", pos: "n" },
    { word: "circumscribe", meaning: "限制 / 畫界線", pos: "n" }
  ],
  4: [
    { word: "circumvent", meaning: "規避 / 繞過", pos: "n" },
    { word: "clamor", meaning: "喧鬧 / 叫嚷", pos: "n" },
    { word: "cleave", meaning: "劈開 / 緊貼", pos: "n" },
    { word: "cobbler", meaning: "鞋匠", pos: "n" },
    { word: "cogent", meaning: "有說服力的 / 令人信服的", pos: "n" },
    { word: "cognizant", meaning: "知道的 / 意識到的", pos: "n" },
    { word: "commensurate", meaning: "相稱的 / 相當的", pos: "n" },
    { word: "complement", meaning: "補充物 / 補足", pos: "n" },
    { word: "compunction", meaning: "內疚 / 悔恨", pos: "n" },
    { word: "concomitant", meaning: "伴隨的 / 同時發生的", pos: "n" },
    { word: "conduit", meaning: "導管 / 管道", pos: "n" },
    { word: "conflagration", meaning: "大火 / 戰火", pos: "n" },
    { word: "congruity", meaning: "一致 / 適合", pos: "n" },
    { word: "connive", meaning: "縱容 / 默許", pos: "n" },
    { word: "consign", meaning: "委託 / 交付", pos: "n" },
    { word: "constituent", meaning: "成分 / 選民", pos: "n" },
    { word: "construe", meaning: "解釋 / 理解為", pos: "n" },
    { word: "contusion", meaning: "挫傷 / 瘀傷", pos: "n" },
    { word: "contrite", meaning: "悔罪的 / 痛悔的", pos: "n" },
    { word: "contentious", meaning: "有爭議的 / 好爭吵的", pos: "n" }
  ],
  5: [
    { word: "contravene", meaning: "違反 / 抵觸", pos: "n" },
    { word: "convivial", meaning: "歡樂的 / 友好的", pos: "n" },
    { word: "corpulence", meaning: "肥胖 / 臃腫", pos: "n" },
    { word: "covet", meaning: "貪求 / 覬覦", pos: "n" },
    { word: "cupidity", meaning: "貪婪 / 貪財", pos: "n" },
    { word: "dearth", meaning: "缺乏 / 稀少", pos: "n" },
    { word: "debacle", meaning: "慘敗 / 崩潰", pos: "n" },
    { word: "debauch", meaning: "墮落 / 放蕩", pos: "n" },
    { word: "debunk", meaning: "揭穿 / 暴露", pos: "n" },
    { word: "defunct", meaning: "死亡的 / 廢止的", pos: "n" },
    { word: "demagogue", meaning: "煽動者 / 蠱惑民心的政客", pos: "n" },
    { word: "denigrate", meaning: "貶低 / 詆毀", pos: "n" },
    { word: "derivative", meaning: "衍生物 / 派生的", pos: "n" },
    { word: "despot", meaning: "專制君主 / 暴君", pos: "n" },
    { word: "diaphanous", meaning: "透明的 / 精緻的", pos: "n" },
    { word: "didactic", meaning: "說教的 / 教誨的", pos: "n" },
    { word: "dirge", meaning: "輓歌 / 哀樂", pos: "n" },
    { word: "disaffected", meaning: "不滿的 / 叛逆的", pos: "n" },
    { word: "discomfit", meaning: "使窘迫 / 挫敗", pos: "n" },
    { word: "disparate", meaning: "不同的 / 異類的", pos: "n" }
  ],
  6: [
    { word: "dispel", meaning: "驅散 / 消除", pos: "n" },
    { word: "disrepute", meaning: "聲名狼藉 / 壞名聲", pos: "n" },
    { word: "divisive", meaning: "引起分歧的 / 導致分裂的", pos: "n" },
    { word: "dogmatic", meaning: "教條的 / 武斷的", pos: "n" },
    { word: "dour", meaning: "嚴厲的 / 陰沉的", pos: "n" },
    { word: "duplicity", meaning: "口是心非 / 欺騙", pos: "n" },
    { word: "duress", meaning: "脅迫 / 壓力", pos: "n" },
    { word: "eclectic", meaning: "折衷的 / 綜合的", pos: "n" },
    { word: "edict", meaning: "法令 / 佈告", pos: "n" },
    { word: "ebullient", meaning: "熱情洋溢的 / 沸騰的", pos: "n" },
    { word: "egregious", meaning: "極壞的 / 令人震驚的", pos: "n" },
    { word: "elegy", meaning: "輓歌 / 哀歌", pos: "n" },
    { word: "elicit", meaning: "引出 / 探出", pos: "n" },
    { word: "embezzlement", meaning: "貪污 / 盜用", pos: "n" },
    { word: "emend", meaning: "校訂 / 修改", pos: "n" },
    { word: "emollient", meaning: "潤膚劑 / 緩和的", pos: "n" },
    { word: "empirical", meaning: "經驗主義的 / 實證的", pos: "n" },
    { word: "emulate", meaning: "效仿 / 模仿", pos: "n" },
    { word: "enervate", meaning: "使衰弱 / 使失去活力", pos: "n" },
    { word: "enfranchise", meaning: "給予選舉權 / 解放", pos: "n" }
  ],
  7: [
    { word: "engender", meaning: "產生 / 引起", pos: "n" },
    { word: "ephemeral", meaning: "短暫的 / 朝生暮死的", pos: "n" },
    { word: "epistolary", meaning: "書信的 / 書信體的", pos: "n" },
    { word: "equanimity", meaning: "平靜 / 鎮定", pos: "n" },
    { word: "equivocal", meaning: "模稜兩可的 / 含糊的", pos: "n" },
    { word: "espouse", meaning: "支持 / 擁護", pos: "n" },
    { word: "evanescent", meaning: "逐漸消失的 / 短暫的", pos: "n" },
    { word: "evince", meaning: "表明 / 顯示", pos: "n" },
    { word: "exacerbate", meaning: "惡化 / 加劇", pos: "n" },
    { word: "exhort", meaning: "勸告 / 勉勵", pos: "n" },
    { word: "execrable", meaning: "劣等的 / 該咒罵的", pos: "n" },
    { word: "exigent", meaning: "緊急的 / 迫切的", pos: "n" },
    { word: "expedient", meaning: "權宜之計 / 有利的", pos: "n" },
    { word: "expiate", meaning: "贖罪 / 補償", pos: "n" },
    { word: "expunge", meaning: "刪除 / 抹去", pos: "n" },
    { word: "extraneous", meaning: "無關的 / 外來的", pos: "n" },
    { word: "extol", meaning: "讚美 / 頌揚", pos: "n" },
    { word: "extant", meaning: "現存的 / 尚存的", pos: "n" },
    { word: "expurgate", meaning: "刪除（不當內容） / 淨化", pos: "n" },
    { word: "fallacious", meaning: "謬誤的 / 騙人的", pos: "n" }
  ],
  8: [
    { word: "fatuous", meaning: "愚笨的 / 昏庸的", pos: "n" },
    { word: "fetter", meaning: "束縛 / 腳鐐", pos: "n" },
    { word: "flagrant", meaning: "明目張膽的 / 惡名昭彰的", pos: "n" },
    { word: "foil", meaning: "阻撓 / 挫敗", pos: "n" },
    { word: "forbearance", meaning: "忍耐 / 寬容", pos: "n" },
    { word: "fortuitous", meaning: "偶然的 / 幸運的", pos: "n" },
    { word: "fractious", meaning: "易怒的 / 倔強的", pos: "n" },
    { word: "garrulous", meaning: "喋喋不休的 / 饒舌的", pos: "n" },
    { word: "gourmand", meaning: "貪吃者 / 饕客", pos: "n" },
    { word: "grandiloquent", meaning: "誇張的 / 浮誇的", pos: "n" },
    { word: "gratuitous", meaning: "無緣無故的 / 免費的", pos: "n" },
    { word: "hapless", meaning: "倒霉的 / 不幸的", pos: "n" },
    { word: "hegemony", meaning: "霸權 / 領導權", pos: "n" },
    { word: "heterogenous", meaning: "異類的 / 混合的", pos: "n" },
    { word: "iconoclast", meaning: "偶像破壞者 / 反傳統者", pos: "n" },
    { word: "idiosyncratic", meaning: "特質的 / 獨特的", pos: "n" },
    { word: "impecunious", meaning: "貧窮的 / 一文不名的", pos: "n" },
    { word: "impetuous", meaning: "衝動的 / 魯莽的", pos: "n" },
    { word: "impinge", meaning: "侵犯 / 撞擊", pos: "n" },
    { word: "impute", meaning: "歸咎於 / 歸因於", pos: "n" }
  ],
  9: [
    { word: "inane", meaning: "空洞的 / 愚蠢的", pos: "n" },
    { word: "inchoate", meaning: "早期的 / 未成形的", pos: "n" },
    { word: "incontrovertible", meaning: "無可辯駁的 / 不容置疑的", pos: "n" },
    { word: "incumbent", meaning: "義不容辭的 / 現任的", pos: "n" },
    { word: "inexorable", meaning: "不可阻擋的 / 無情的", pos: "n" },
    { word: "inimical", meaning: "敵意的 / 有害的", pos: "n" },
    { word: "injunction", meaning: "命令 / 禁令", pos: "n" },
    { word: "inoculate", meaning: "接種 / 灌輸", pos: "n" },
    { word: "insidious", meaning: "潛伏的 / 陰險的", pos: "n" },
    { word: "instigate", meaning: "煽動 / 唆使", pos: "n" },
    { word: "insurgent", meaning: "叛亂者 / 起義者", pos: "n" },
    { word: "interlocutor", meaning: "對話者 / 談話對手", pos: "n" },
    { word: "intimation", meaning: "暗示 / 透露", pos: "n" },
    { word: "inure", meaning: "使習慣於 / 生效", pos: "n" },
    { word: "invective", meaning: "謾罵 / 惡言", pos: "n" },
    { word: "intransigent", meaning: "不妥協的 / 固執的", pos: "n" },
    { word: "inveterate", meaning: "根深蒂固的 / 積習的", pos: "n" },
    { word: "irreverence", meaning: "不敬 / 輕蔑", pos: "n" },
    { word: "knell", meaning: "喪鐘聲 / 凶兆", pos: "n" },
    { word: "laconic", meaning: "簡潔的 / 寡言的", pos: "n" }
  ],
  10: [
    { word: "largesse", meaning: "慷慨 / 恩賜", pos: "n" },
    { word: "legerdemain", meaning: "戲法 / 騙術", pos: "n" },
    { word: "libertarian", meaning: "自由意志主義者 / 倡導自由的人", pos: "n" },
    { word: "licentious", meaning: "放蕩的 / 淫亂的", pos: "n" },
    { word: "linchpin", meaning: "關鍵人物 / 樞紐", pos: "n" },
    { word: "litigant", meaning: "訴訟當事人", pos: "n" },
    { word: "maelstrom", meaning: "大漩渦 / 大混亂", pos: "n" },
    { word: "maudlin", meaning: "傷感的 / 容易流淚的", pos: "n" },
    { word: "maverick", meaning: "特立獨行者 / 不守常規的人", pos: "n" },
    { word: "mawkish", meaning: "無病呻吟的 / 令人作嘔的", pos: "n" },
    { word: "maxim", meaning: "格言 / 箴言", pos: "n" },
    { word: "mendacious", meaning: "虛假的 / 說謊的", pos: "n" },
    { word: "modicum", meaning: "少量 / 一點點", pos: "n" },
    { word: "morass", meaning: "沼澤 / 困境", pos: "n" },
    { word: "mores", meaning: "風俗 / 習慣", pos: "n" },
    { word: "munificent", meaning: "慷慨的 / 豐厚的", pos: "n" },
    { word: "multifarious", meaning: "多種多樣的 / 各式各樣的", pos: "n" },
    { word: "nadir", meaning: "最低點 / 深淵", pos: "n" },
    { word: "negligent", meaning: "疏忽的 / 粗心的", pos: "n" },
    { word: "neophyte", meaning: "新手 / 初學者", pos: "n" }
  ],
  11: [
    { word: "noisome", meaning: "惡臭的 / 有害的", pos: "n" },
    { word: "noxious", meaning: "有毒的 / 有害的", pos: "n" },
    { word: "obdurate", meaning: "頑固的 / 執拗的", pos: "n" },
    { word: "obfuscate", meaning: "使模糊 / 使困惑", pos: "n" },
    { word: "obstreperous", meaning: "喧鬧的 / 難駕馭的", pos: "n" },
    { word: "officious", meaning: "多管閒事的 / 愛發號施令的", pos: "n" },
    { word: "onerous", meaning: "繁重的 / 麻煩的", pos: "n" },
    { word: "ostensible", meaning: "表面的 / 假裝的", pos: "n" },
    { word: "ostracism", meaning: "排斥 / 放逐", pos: "n" },
    { word: "palliate", meaning: "減輕 / 掩飾", pos: "n" },
    { word: "panacea", meaning: "萬靈藥 / 解決所有問題的方法", pos: "n" },
    { word: "paradigm", meaning: "範例 / 模範", pos: "n" },
    { word: "pariah", meaning: "賤民 / 被社會遺棄者", pos: "n" },
    { word: "partisan", meaning: "黨派的 / 偏袒的", pos: "n" },
    { word: "paucity", meaning: "缺乏 / 稀少", pos: "n" },
    { word: "pejorative", meaning: "貶義的 / 輕蔑的", pos: "n" },
    { word: "pellucid", meaning: "清澈的 / 易懂的", pos: "n" },
    { word: "penchant", meaning: "傾向 / 嗜好", pos: "n" },
    { word: "penurious", meaning: "吝嗇的 / 貧窮的", pos: "n" },
    { word: "pert", meaning: "俏皮的 / 魯莽的", pos: "n" }
  ],
  12: [
    { word: "pernicious", meaning: "有害的 / 致命的", pos: "n" },
    { word: "pertinacious", meaning: "頑固的 / 執拗的", pos: "n" },
    { word: "phlegmatic", meaning: "冷靜的 / 遲鈍的", pos: "n" },
    { word: "philanthropic", meaning: "慈善的 / 博愛的", pos: "n" },
    { word: "pithy", meaning: "簡練的 / 精闢的", pos: "n" },
    { word: "platitude", meaning: "老生常談 / 陳詞濫調", pos: "n" },
    { word: "plaudit", meaning: "喝采 / 讚賞", pos: "n" },
    { word: "plenitude", meaning: "豐富 / 充足", pos: "n" },
    { word: "plethora", meaning: "過剩 / 泛濫", pos: "n" },
    { word: "portent", meaning: "預兆 / 凶兆", pos: "n" },
    { word: "potentate", meaning: "統治者 / 君主", pos: "n" },
    { word: "preclude", meaning: "排除 / 阻止", pos: "n" },
    { word: "predilection", meaning: "偏好 / 嗜好", pos: "n" },
    { word: "preponderance", meaning: "優勢 / 多數", pos: "n" },
    { word: "presage", meaning: "預示 / 預兆", pos: "n" },
    { word: "probity", meaning: "誠實 / 正直", pos: "n" },
    { word: "proclivity", meaning: "傾向 / 癖性", pos: "n" },
    { word: "profligate", meaning: "揮霍的 / 墮落的", pos: "n" },
    { word: "promulgate", meaning: "公布 / 頒布", pos: "n" },
    { word: "proscribe", meaning: "禁止 / 放逐", pos: "n" }
  ],
  13: [
    { word: "protean", meaning: "千變萬化的 / 多變的", pos: "n" },
    { word: "prurient", meaning: "好色的 / 淫慾的", pos: "n" },
    { word: "puerile", meaning: "幼稚的 / 孩童的", pos: "n" },
    { word: "pugnacious", meaning: "好鬥的 / 好戰的", pos: "n" },
    { word: "pulchritude", meaning: "美麗 / 標緻", pos: "n" },
    { word: "punctilious", meaning: "一絲不苟的 / 拘泥細節的", pos: "n" },
    { word: "quaint", meaning: "古雅的 / 奇特的", pos: "n" },
    { word: "quixotic", meaning: "不切實際的 / 唐吉訶德式的", pos: "n" },
    { word: "quandary", meaning: "困境 / 窘境", pos: "n" },
    { word: "recalcitrant", meaning: "桀驁不馴的 / 頑抗的", pos: "n" },
    { word: "redoubtable", meaning: "可怕的 / 令人敬畏的", pos: "n" },
    { word: "relegate", meaning: "降級 / 委託", pos: "n" },
    { word: "remiss", meaning: "怠忽職守的 / 疏忽的", pos: "n" },
    { word: "reprieve", meaning: "緩刑 / 暫緩", pos: "n" },
    { word: "reprobate", meaning: "墮落者 / 惡棍", pos: "n" },
    { word: "rescind", meaning: "廢除 / 取消", pos: "n" },
    { word: "requisition", meaning: "徵用 / 需求", pos: "n" },
    { word: "rife", meaning: "充斥的 / 普遍的", pos: "n" },
    { word: "sanctimonious", meaning: "假裝虔誠的 / 偽善的", pos: "n" },
    { word: "sanguine", meaning: "樂觀的 / 紅潤的", pos: "n" }
  ],
  14: [
    { word: "scurrilous", meaning: "粗俗的 / 誹謗的", pos: "n" },
    { word: "semaphore", meaning: "臂板信號 / 信號標", pos: "n" },
    { word: "serendipity", meaning: "機緣巧合 / 意外發現", pos: "n" },
    { word: "sobriety", meaning: "清醒 / 莊重", pos: "n" },
    { word: "solicitous", meaning: "關切的 / 掛念的", pos: "n" },
    { word: "solipsism", meaning: "唯我論", pos: "n" },
    { word: "spurious", meaning: "偽造的 / 欺騙的", pos: "n" },
    { word: "staid", meaning: "沉著的 / 穩重的", pos: "n" },
    { word: "stolid", meaning: "遲鈍的 / 缺乏熱情的", pos: "n" },
    { word: "subjugate", meaning: "征服 / 降伏", pos: "n" },
    { word: "surfeit", meaning: "過量 / 飲食過度", pos: "n" },
    { word: "surreptitious", meaning: "秘密的 / 鬼鬼祟祟的", pos: "n" },
    { word: "swarthy", meaning: "黝黑的 / 黑皮膚的", pos: "n" },
    { word: "tangential", meaning: "離題的 / 膚淺的", pos: "n" },
    { word: "tome", meaning: "大部頭書 / 巨著", pos: "n" },
    { word: "toady", meaning: "諂媚者 / 拍馬屁的人", pos: "n" },
    { word: "torpid", meaning: "遲鈍的 / 懶散的", pos: "n" },
    { word: "travesty", meaning: "拙劣的模仿 / 嘲弄", pos: "n" },
    { word: "trenchant", meaning: "銳利的 / 一針見血的", pos: "n" },
    { word: "trite", meaning: "陳腐的 / 平庸的", pos: "n" }
  ],
  15: [
    { word: "truculent", meaning: "好鬥的 / 殘暴的", pos: "n" },
    { word: "turpitude", meaning: "卑鄙 / 墮落", pos: "n" },
    { word: "ubiquitous", meaning: "無所不在的 / 普遍存在的", pos: "n" },
    { word: "umbrage", meaning: "生氣 / 怨恨", pos: "n" },
    { word: "upbraid", meaning: "責罵 / 訓斥", pos: "n" },
    { word: "utilitarian", meaning: "功利的 / 實用的", pos: "n" },
    { word: "veracity", meaning: "誠實 / 真實", pos: "n" },
    { word: "vestige", meaning: "遺跡 / 殘餘", pos: "n" },
    { word: "vicissitude", meaning: "變遷 / 盛衰", pos: "n" },
    { word: "vilify", meaning: "誹謗 / 貶低", pos: "n" },
    { word: "virtuoso", meaning: "藝術大師 / 名家", pos: "n" },
    { word: "vitriolic", meaning: "尖酸刻薄的 / 惡意的", pos: "n" },
    { word: "vituperate", meaning: "謾罵 / 責罵", pos: "n" },
    { word: "vociferous", meaning: "喧嘩的 / 大聲叫嚷的", pos: "n" },
    { word: "wanton", meaning: "肆無忌憚的 / 淫蕩的", pos: "n" },
    { word: "winsome", meaning: "迷人的 / 惹人喜愛的", pos: "n" },
    { word: "yoke", meaning: "結合 / 束縛", pos: "n" },
    { word: "zephyr", meaning: "微風 / 和風", pos: "n" },
    { word: "wily", meaning: "狡猾的 / 詭計多端的", pos: "n" },
    { word: "tirade", meaning: "長篇激烈的演說 / 抨擊", pos: "n" }
  ]
};

export function getWordSet(round: number): Word[] {
  // If we run out of sets, loop back
  const setKeys = Object.keys(wordSets).map(Number).sort((a, b) => a - b);
  const maxSet = setKeys[setKeys.length - 1];
  const actualRound = ((round - 1) % maxSet) + 1;
  return wordSets[actualRound];
}
