export interface Word {
  word: string;
  meaning: string;
  pos: string; // Part of speech
}

// 重新打包後的題庫，每組固定 30 個單字
export const wordSets: Record<number, Word[]> = {
  1: [
    { word: "enervate", meaning: "使衰弱 / 使失去活力", pos: "v" },
    { word: "equanimity", meaning: "沉著 / 平靜", pos: "n" },
    { word: "frenzy", meaning: "瘋開", pos: "n" },
    { word: "cosmopolitan", meaning: "世界性的 / 國際的", pos: "adj" },
    { word: "hagiography", meaning: "聖徒傳記 / 捧場傳記", pos: "n" },
    { word: "impervious", meaning: "不受影響的", pos: "adj" },
    { word: "badinage", meaning: "打趣 / 玩笑", pos: "n" },
    { word: "confrere", meaning: "同行 / 同僚", pos: "n" },
    { word: "peremptory", meaning: "專橫的", pos: "adj" },
    { word: "ambit", meaning: "範圍 / 界限", pos: "n" },
    { word: "stifled", meaning: "窒息的", pos: "adj" },
    { word: "partisan", meaning: "偏袒的 / 黨派性的", pos: "adj" },
    { word: "vituperate", meaning: "謾罵 / 責罵", pos: "v" },
    { word: "antagonize", meaning: "惹怒 / 引起敵意", pos: "v" },
    { word: "nebulous", meaning: "模糊的 / 星雲狀的", pos: "adj" },
    { word: "appellation", meaning: "名稱 / 稱呼", pos: "n" },
    { word: "decrepit", meaning: "衰老的 / 破舊的", pos: "adj" },
    { word: "paean", meaning: "讚美歌 / 歡樂歌", pos: "n" },
    { word: "pejorative", meaning: "貶義的 / 輕蔑的", pos: "adj" },
    { word: "circumlocute", meaning: "婉轉說 / 迂迴地說", pos: "v" },
    { word: "interregnum", meaning: "過渡期", pos: "n" },
    { word: "obloquy", meaning: "辱罵", pos: "n" },
    { word: "elucubrate", meaning: "刻苦鑽研 / 挑燈夜作", pos: "v" },
    { word: "abattoir", meaning: "屠宰場", pos: "n" },
    { word: "rancorous", meaning: "怨恨的 / 滿懷惡意的", pos: "adj" },
    { word: "craven", meaning: "膽小的 / 卑怯的", pos: "adj" },
    { word: "laconic", meaning: "簡短的 / 簡潔的", pos: "adj" },
    { word: "excoriate", meaning: "嚴厲譴責 / 擦破皮", pos: "v" },
    { word: "augur", meaning: "預言 / 占卜", pos: "v" },
    { word: "chicanery", meaning: "欺詐 / 狡辯", pos: "n" }
  ],
  2: [
    { word: "extensive", meaning: "廣泛的", pos: "adj" },
    { word: "gaffe", meaning: "失禮", pos: "n" },
    { word: "clinamen", meaning: "偏斜 / 傾向", pos: "n" },
    { word: "querulous", meaning: "愛抱怨的 / 易怒的", pos: "adj" },
    { word: "quotidian", meaning: "每日的", pos: "adj" },
    { word: "fecund", meaning: "多產的 / 肥沃的", pos: "adj" },
    { word: "peccadillo", meaning: "小過失", pos: "n" },
    { word: "capitulate", meaning: "投降 / 屈服", pos: "v" },
    { word: "prevaricate", meaning: "支吾其詞", pos: "v" },
    { word: "fulminate", meaning: "嚴厲譴責 / 爆發", pos: "v" },
    { word: "fulsome", meaning: "過度恭維的 / 令人生厭的", pos: "adj" },
    { word: "cariosity", meaning: "齲齒 / 腐朽", pos: "n" },
    { word: "incongruous", meaning: "不協調的", pos: "adj" },
    { word: "evanescent", meaning: "瞬息萬變的 / 稍縱即逝的", pos: "adj" },
    { word: "inchoate", meaning: "早期的 / 剛開始的", pos: "adj" },
    { word: "lacuna", meaning: "空白 / 缺失", pos: "n" },
    { word: "apothegm", meaning: "箴言 / 格言", pos: "n" },
    { word: "bilious", meaning: "壞脾氣的 / 膽汁的", pos: "adj" },
    { word: "finesse", meaning: "技巧 / 策略", pos: "n" },
    { word: "nictitate", meaning: "眨眼", pos: "v" },
    { word: "convivial", meaning: "歡樂的 / 友好的", pos: "adj" },
    { word: "hackneyed", meaning: "陳腐的 / 老生常談的", pos: "adj" },
    { word: "cerulean", meaning: "蔚藍的 / 天藍色的", pos: "adj" },
    { word: "exhort", meaning: "勸告 / 勉勵", pos: "v" },
    { word: "avarice", meaning: "貪婪", pos: "n" },
    { word: "bedizen", meaning: "俗麗地打扮", pos: "v" },
    { word: "ambuscado", meaning: "埋伏 / 伏兵", pos: "n" },
    { word: "vapid", meaning: "乏味的 / 枯燥的", pos: "adj" },
    { word: "eclectic", meaning: "折衷的 / 綜合的", pos: "adj" },
    { word: "imperative", meaning: "必要的", pos: "adj" }
  ],
  3: [
    { word: "inane", meaning: "空洞的 / 愚蠢的", pos: "adj" },
    { word: "coruscate", meaning: "閃耀 / 閃爍", pos: "v" },
    { word: "redoubtable", meaning: "可怕的 / 令人敬畏的", pos: "adj" },
    { word: "factotum", meaning: "雜役 / 總管", pos: "n" },
    { word: "demure", meaning: "端莊的 / 羞怯的", pos: "adj" },
    { word: "atrabilious", meaning: "憂鬱的 / 易怒的", pos: "adj" },
    { word: "gauche", meaning: "笨拙的", pos: "adj" },
    { word: "conifer", meaning: "針葉樹", pos: "n" },
    { word: "zoilism", meaning: "嚴苛的批評", pos: "n" },
    { word: "exonerate", meaning: "證明無罪", pos: "v" },
    { word: "verbiage", meaning: "冗詞", pos: "n" },
    { word: "obstreperous", meaning: "吵鬧的 / 難以控制的", pos: "adj" },
    { word: "impugn", meaning: "責難", pos: "v" },
    { word: "cull", meaning: "挑選 / 剔除", pos: "v" },
    { word: "obelisk", meaning: "方尖碑", pos: "n" },
    { word: "idolatrous", meaning: "盲目崇拜的", pos: "adj" },
    { word: "subjugate", meaning: "征服 / 降伏", pos: "v" },
    { word: "chiasmus", meaning: "交叉配列法", pos: "n" },
    { word: "animadversion", meaning: "批評 / 非難", pos: "n" },
    { word: "canorous", meaning: "音調優美的 / 響亮的", pos: "adj" },
    { word: "obfuscate", meaning: "使模糊 / 使困惑", pos: "v" },
    { word: "quibble", meaning: "狡辯", pos: "v" },
    { word: "ecdysis", meaning: "蛻皮 / 換羽", pos: "n" },
    { word: "asceticism", meaning: "苦行 / 禁慾主義", pos: "n" },
    { word: "zephyr", meaning: "微風 / 和風", pos: "n" },
    { word: "gregarious", meaning: "社交的 / 群居的", pos: "adj" },
    { word: "crepuscular", meaning: "拂曉的 / 朦朧的", pos: "adj" },
    { word: "maculate", meaning: "玷污的 / 有斑點的", pos: "adj" },
    { word: "ubiety", meaning: "所在 / 位置", pos: "n" },
    { word: "gossamer", meaning: "輕薄的 / 虛無飄渺的", pos: "adj" }
  ],
  4: [
    { word: "ostentatious", meaning: "炫耀的 / 誇示的", pos: "adj" },
    { word: "vex", meaning: "使煩惱 / 惱怒", pos: "v" },
    { word: "dolt", meaning: "傻瓜 / 笨蛋", pos: "n" },
    { word: "gallinaceous", meaning: "雞形的", pos: "adj" },
    { word: "abstemious", meaning: "有節制的 / 簡樸的", pos: "adj" },
    { word: "ardor", meaning: "熱情 / 熱心", pos: "n" },
    { word: "deglutition", meaning: "吞嚥", pos: "n" },
    { word: "fawn", meaning: "討好 / 奉承", pos: "v" },
    { word: "parvenu", meaning: "暴發戶 / 新貴", pos: "n" },
    { word: "artless", meaning: "天真的 / 樸實的", pos: "adj" },
    { word: "obviate", meaning: "排除", pos: "v" },
    { word: "turpitude", meaning: "卑劣 / 墮落", pos: "n" },
    { word: "casuistry", meaning: "詭辯 / 決疑法", pos: "n" },
    { word: "stupefy", meaning: "使麻木 / 使驚呆", pos: "v" },
    { word: "desultory", meaning: "漫無目的的 / 散漫的", pos: "adj" },
    { word: "litigant", meaning: "訴訟當事人", pos: "n" },
    { word: "decimate", meaning: "大批殺害 / 大幅削減", pos: "v" },
    { word: "elicit", meaning: "引出 / 探出", pos: "v" },
    { word: "affable", meaning: "和藹可親的", pos: "adj" },
    { word: "deictic", meaning: "指示的 / 證明的", pos: "adj" },
    { word: "striate", meaning: "加條紋", pos: "v" },
    { word: "ensue", meaning: "接著發生 / 因而產生", pos: "v" },
    { word: "jest", meaning: "笑話", pos: "n" },
    { word: "descry", meaning: "看見 / 發現", pos: "v" },
    { word: "lassitude", meaning: "疲倦 / 懈怠", pos: "n" },
    { word: "juxtapose", meaning: "並列", pos: "v" },
    { word: "curmudgeon", meaning: "脾氣壞的人", pos: "n" },
    { word: "arrant", meaning: "徹頭徹尾的 / 極惡的", pos: "adj" },
    { word: "conduit", meaning: "導管 / 管道", pos: "n" },
    { word: "clemency", meaning: "寬容 / 仁慈", pos: "n" }
  ],
  5: [
    { word: "occlude", meaning: "阻塞 / 封閉", pos: "v" },
    { word: "fatuous", meaning: "愚蠢的 / 昏庸的", pos: "adj" },
    { word: "perfidious", meaning: "不忠的", pos: "adj" },
    { word: "vicissitude", meaning: "變遷 / 盛衰", pos: "n" },
    { word: "infiltrate", meaning: "滲透", pos: "v" },
    { word: "anachronism", meaning: "時代錯誤 / 過時的人或事", pos: "n" },
    { word: "pedantic", meaning: "迂腐的 / 學究氣的", pos: "adj" },
    { word: "anathema", meaning: "令人痛恨的事物 / 詛咒", pos: "n" },
    { word: "redolent", meaning: "芬芳的 / 令人想起的", pos: "adj" },
    { word: "orotund", meaning: "響亮的", pos: "adj" },
    { word: "berate", meaning: "嚴責 / 痛罵", pos: "v" },
    { word: "debonair", meaning: "溫文爾雅的 / 愉快的", pos: "adj" },
    { word: "eudaemonia", meaning: "幸福 / 繁榮", pos: "n" },
    { word: "acerbic", meaning: "尖刻的 / 苦澀的", pos: "adj" },
    { word: "lull", meaning: "使平靜", pos: "v" },
    { word: "iniquitous", meaning: "極不公正的", pos: "adj" },
    { word: "extempore", meaning: "即席的", pos: "adj" },
    { word: "catharsis", meaning: "宣洩 / 淨化", pos: "n" },
    { word: "enlist", meaning: "徵募", pos: "v" },
    { word: "bellicose", meaning: "好戰的 / 好鬥的", pos: "adj" },
    { word: "perfunctory", meaning: "敷衍的", pos: "adj" },
    { word: "quiddity", meaning: "本質 / 實質", pos: "n" },
    { word: "albescent", meaning: "發白的 / 帶白的", pos: "adj" },
    { word: "phlegmatic", meaning: "冷淡的 / 鎮定的", pos: "adj" },
    { word: "affront", meaning: "冒犯 / 侮辱", pos: "v" },
    { word: "concoct", meaning: "調製 / 編造", pos: "v" },
    { word: "blithe", meaning: "無憂無慮的 / 愉快的", pos: "adj" },
    { word: "obeisance", meaning: "敬禮", pos: "n" },
    { word: "coprolalia", meaning: "穢語症", pos: "n" },
    { word: "drivel", meaning: "蠢話 / 胡言亂語", pos: "n" }
  ],
  6: [
    { word: "abscond", meaning: "潛逃 / 逃跑", pos: "v" },
    { word: "ogle", meaning: "拋媚眼", pos: "v" },
    { word: "ugsome", meaning: "可怕的 / 令人厭惡的", pos: "adj" },
    { word: "accidie", meaning: "怠惰 / 精神抑鬱", pos: "n" },
    { word: "aplomb", meaning: "沉著 / 泰然自若", pos: "n" },
    { word: "sanctimonious", meaning: "假裝虔誠的 / 偽善的", pos: "adj" },
    { word: "gainsay", meaning: "否認 / 反駁", pos: "v" },
    { word: "gloat", meaning: "幸災樂禍", pos: "v" },
    { word: "incarnadine", meaning: "肉色的 / 血紅的", pos: "adj" },
    { word: "obtrusive", meaning: "冒失的", pos: "adj" },
    { word: "prognosticate", meaning: "預言 / 預示", pos: "v" },
    { word: "adulterate", meaning: "摻雜", pos: "v" },
    { word: "acrimonious", meaning: "尖刻的 / 嚴厲的", pos: "adj" },
    { word: "pulchritude", meaning: "美麗 / 標緻", pos: "n" },
    { word: "lagniappe", meaning: "贈品 / 額外的好處", pos: "n" },
    { word: "sternutation", meaning: "打噴嚏", pos: "n" },
    { word: "placate", meaning: "安撫", pos: "v" },
    { word: "cruciation", meaning: "折磨 / 痛苦", pos: "n" },
    { word: "mace", meaning: "權杖", pos: "n" },
    { word: "comity", meaning: "禮讓 / 友誼", pos: "n" },
    { word: "efface", meaning: "抹去", pos: "v" },
    { word: "apodictic", meaning: "必然的 / 不容置疑的", pos: "adj" },
    { word: "dastard", meaning: "懦夫 / 卑鄙的人", pos: "n" },
    { word: "mulct", meaning: "罰款 / 詐取", pos: "v" },
    { word: "castigate", meaning: "嚴厲責罵", pos: "v" },
    { word: "palaver", meaning: "空談 / 諂媚", pos: "n" },
    { word: "stigma", meaning: "恥辱 / 污名", pos: "n" },
    { word: "fulmination", meaning: "嚴懲 / 爆發", pos: "n" },
    { word: "conjure", meaning: "變戲法 / 召喚", pos: "v" },
    { word: "gavel", meaning: "小槌", pos: "n" }
  ],
  7: [
    { word: "denigrate", meaning: "貶低 / 詆毀", pos: "v" },
    { word: "glib", meaning: "油腔滑調的", pos: "adj" },
    { word: "inure", meaning: "使習慣於 / 生效", pos: "v" },
    { word: "fiat", meaning: "命令 / 許可", pos: "n" },
    { word: "fetter", meaning: "束縛 / 羈絆", pos: "v" },
    { word: "anfractuous", meaning: "迂迴的 / 彎曲的", pos: "adj" },
    { word: "concinnity", meaning: "諧調 / 雅緻", pos: "n" },
    { word: "limn", meaning: "描繪 / 畫", pos: "v" },
    { word: "cobbler", meaning: "鞋匠", pos: "n" },
    { word: "facetious", meaning: "詼諧的 / 愛開玩笑的", pos: "adj" },
    { word: "accoutrement", meaning: "裝備 / 配備", pos: "n" },
    { word: "lope", meaning: "大步慢跑", pos: "v" },
    { word: "acolyte", meaning: "助手 / 侍從", pos: "n" },
    { word: "prolix", meaning: "囉嗦的 / 冗長的", pos: "adj" },
    { word: "scintillating", meaning: "閃爍的 / 才華橫溢的", pos: "adj" },
    { word: "parsimonious", meaning: "吝嗇的", pos: "adj" },
    { word: "brood", meaning: "沉思 / 籠罩", pos: "v" },
    { word: "ignominious", meaning: "可恥的 / 恥辱的", pos: "adj" },
    { word: "libertine", meaning: "放蕩者 / 浪子", pos: "n" },
    { word: "cachinnation", meaning: "狂笑 / 哈哈大笑", pos: "n" },
    { word: "colubrine", meaning: "蛇的 / 狡猾的", pos: "adj" },
    { word: "jejune", meaning: "枯燥無味的 / 幼稚的", pos: "adj" },
    { word: "dour", meaning: "嚴厲的 / 陰沉的", pos: "adj" },
    { word: "esoteric", meaning: "深奧的", pos: "adj" },
    { word: "debauchery", meaning: "放蕩 / 淫逸", pos: "n" },
    { word: "extenuate", meaning: "減輕 (罪過) / 為...找藉口", pos: "v" },
    { word: "cogitate", meaning: "思考 / 沉思", pos: "v" },
    { word: "clandestine", meaning: "秘密的 / 暗中的", pos: "adj" },
    { word: "intractable", meaning: "難熬的 / 倔強的", pos: "adj" },
    { word: "farrago", meaning: "混雜物 / 大雜燴", pos: "n" }
  ],
  8: [
    { word: "solipsism", meaning: "唯我論", pos: "n" },
    { word: "delineate", meaning: "描繪", pos: "v" },
    { word: "moat", meaning: "護城河", pos: "n" },
    { word: "abominate", meaning: "痛恨 / 厭惡", pos: "v" },
    { word: "martinet", meaning: "嚴格執行紀律的人", pos: "n" },
    { word: "fallacious", meaning: "謬誤的 / 欺騙性的", pos: "adj" },
    { word: "amalgamate", meaning: "合併 / 混合", pos: "v" },
    { word: "pert", meaning: "俏皮的 / 魯莽的", pos: "adj" },
    { word: "abase", meaning: "貶低 / 降低", pos: "v" },
    { word: "gravel", meaning: "碎石", pos: "n" },
    { word: "credulity", meaning: "輕信", pos: "n" },
    { word: "attrite", meaning: "磨損的 / 摩擦產生的", pos: "adj" },
    { word: "nihilistic", meaning: "虛無主義的", pos: "adj" },
    { word: "largesse", meaning: "慷慨 / 恩賜", pos: "n" },
    { word: "squelch", meaning: "壓制", pos: "v" },
    { word: "sanguine", meaning: "樂觀的 / 紅潤的", pos: "adj" },
    { word: "buttress", meaning: "支持 / 扶壁", pos: "n" },
    { word: "connive", meaning: "縱容 / 默許", pos: "v" },
    { word: "arcuate", meaning: "弓形的 / 彎曲的", pos: "adj" },
    { word: "preponderance", meaning: "優勢 / 多數", pos: "n" },
    { word: "extemporaneous", meaning: "即席的 / 毫無準備的", pos: "adj" },
    { word: "emancipate", meaning: "解放 / 釋放", pos: "v" },
    { word: "cogent", meaning: "有說服力的 / 強而有力的", pos: "adj" },
    { word: "deferential", meaning: "恭敬的 / 順從的", pos: "adj" },
    { word: "ablution", meaning: "沐浴 / 洗禮", pos: "n" },
    { word: "disquisition", meaning: "論文 / 專題研究", pos: "n" },
    { word: "puissant", meaning: "強大的 / 有權力的", pos: "adj" },
    { word: "axiomatic", meaning: "不言自明的 / 公理的", pos: "adj" },
    { word: "exculpate", meaning: "證明無罪", pos: "v" },
    { word: "ensign", meaning: "艦隊旗 / 少尉", pos: "n" }
  ],
  9: [
    { word: "coruscation", meaning: "閃爍 / 光芒", pos: "n" },
    { word: "erudite", meaning: "博學的", pos: "adj" },
    { word: "afflatus", meaning: "靈感 / 神啟", pos: "n" },
    { word: "bifurcate", meaning: "分支 / 分叉", pos: "v" },
    { word: "impregnable", meaning: "堅不可摧的", pos: "adj" },
    { word: "charlatan", meaning: "騙子 / 冒充內行者", pos: "n" },
    { word: "decorum", meaning: "端莊 / 得體", pos: "n" },
    { word: "capricious", meaning: "反覆無常的", pos: "adj" },
    { word: "wanton", meaning: "放肆的 / 無節制的", pos: "adj" },
    { word: "dross", meaning: "浮渣 / 糟粕", pos: "n" },
    { word: "molt", meaning: "脫毛", pos: "v" },
    { word: "perspicacious", meaning: "敏銳的 / 有洞察力的", pos: "adj" },
    { word: "gelid", meaning: "極冷的 / 冰凍的", pos: "adj" },
    { word: "implacable", meaning: "難以平息的 / 毫不妥協的", pos: "adj" },
    { word: "arable", meaning: "適於耕種的", pos: "adj" },
    { word: "puerile", meaning: "幼稚的 / 愚蠢的", pos: "adj" },
    { word: "spurious", meaning: "偽造的 / 虛假的", pos: "adj" },
    { word: "stolid", meaning: "遲鈍的 / 無動於衷的", pos: "adj" },
    { word: "dilettante", meaning: "業餘愛好者 / 半吊子", pos: "n" },
    { word: "aposematic", meaning: "警戒色的", pos: "adj" },
    { word: "prerogative", meaning: "特權", pos: "n" },
    { word: "bowdlerize", meaning: "刪節 / 淨化", pos: "v" },
    { word: "apercu", meaning: "概觀 / 洞察", pos: "n" },
    { word: "inexorable", meaning: "不可阻擋的 / 無情的", pos: "adj" },
    { word: "lugubrious", meaning: "悲戚的 / 憂鬱的", pos: "adj" },
    { word: "encumber", meaning: "阻礙", pos: "v" },
    { word: "obdurate", meaning: "固執的 / 頑固的", pos: "adj" },
    { word: "imbibe", meaning: "飲 / 吸收", pos: "v" },
    { word: "idiosyncratic", meaning: "特質的 / 獨特的", pos: "adj" },
    { word: "diffident", meaning: "羞怯的", pos: "adj" }
  ],
  10: [
    { word: "tenable", meaning: "站得住腳的 / 可守衛的", pos: "adj" },
    { word: "obtrude", meaning: "強加", pos: "v" },
    { word: "conceit", meaning: "自負", pos: "n" },
    { word: "baneful", meaning: "有害的 / 致命的", pos: "adj" },
    { word: "duress", meaning: "脅迫 / 壓力", pos: "n" },
    { word: "reprobate", meaning: "墮落者 / 惡棍", pos: "n" },
    { word: "consign", meaning: "委託 / 交付", pos: "v" },
    { word: "derelict", meaning: "廢棄的 / 玩忽職守的", pos: "adj" },
    { word: "rasorial", meaning: "扒土覓食的", pos: "adj" },
    { word: "ardent", meaning: "熱情的 / 熱心的", pos: "adj" },
    { word: "hubris", meaning: "傲慢 / 狂妄自大", pos: "n" },
    { word: "adulteration", meaning: "摻雜", pos: "n" },
    { word: "apostate", meaning: "叛教者 / 脫黨者", pos: "n" },
    { word: "hapless", meaning: "倒霉的 / 不幸的", pos: "adj" },
    { word: "insensible", meaning: "無知覺的", pos: "adj" },
    { word: "juggernaut", meaning: "不可抗拒的力量", pos: "n" },
    { word: "condone", meaning: "寬恕 / 赦免", pos: "v" },
    { word: "entreat", meaning: "懇求 / 乞求", pos: "v" },
    { word: "beleaguer", meaning: "圍攻 / 困擾", pos: "v" },
    { word: "probity", meaning: "正直 / 誠實", pos: "n" },
    { word: "imbue", meaning: "灌輸", pos: "v" },
    { word: "repine", meaning: "苦悶 / 抱怨", pos: "v" },
    { word: "encomium", meaning: "讚美", pos: "n" },
    { word: "encroach", meaning: "侵佔", pos: "v" },
    { word: "feral", meaning: "野生的 / 兇猛的", pos: "adj" },
    { word: "lexicon", meaning: "詞典 / 詞彙表", pos: "n" },
    { word: "antediluvian", meaning: "遠古的 / 大洪水以前的", pos: "adj" },
    { word: "corpulent", meaning: "肥胖的", pos: "adj" },
    { word: "execrable", meaning: "劣等的 / 該咒罵的", pos: "adj" },
    { word: "liminality", meaning: "邊緣性 / 過渡狀態", pos: "n" }
  ],
  11: [
    { word: "grovel", meaning: "卑躬屈膝", pos: "v" },
    { word: "precipitous", meaning: "險峻的", pos: "adj" },
    { word: "protean", meaning: "千變萬化的 / 多變的", pos: "adj" },
    { word: "argot", meaning: "隱語 / 黑話", pos: "n" },
    { word: "fractious", meaning: "易怒的 / 難以控制的", pos: "adj" },
    { word: "ennui", meaning: "無聊 / 倦怠", pos: "n" },
    { word: "corrugated", meaning: "呈波浪形的 / 皺褶的", pos: "adj" },
    { word: "syzygy", meaning: "朔望 / 聯合", pos: "n" },
    { word: "dithering", meaning: "猶豫不決", pos: "n" },
    { word: "desiccate", meaning: "使脫水", pos: "v" },
    { word: "annex", meaning: "附加 / 併吞", pos: "v" },
    { word: "germane", meaning: "有密切關係的", pos: "adj" },
    { word: "expurgate", meaning: "刪除（不當內容） / 淨化", pos: "v" },
    { word: "avulsion", meaning: "撕脫 / 剝離", pos: "n" },
    { word: "forestall", meaning: "先發制人 / 預先阻止", pos: "v" },
    { word: "nonplused", meaning: "困惑的", pos: "adj" },
    { word: "cosset", meaning: "溺愛 / 縱容", pos: "v" },
    { word: "edify", meaning: "啟發 / 薰陶", pos: "v" },
    { word: "absquatulate", meaning: "潛逃 / 溜走", pos: "v" },
    { word: "benison", meaning: "祝福 / 賜福", pos: "n" },
    { word: "inveigh", meaning: "猛烈抨擊 / 痛罵", pos: "v" },
    { word: "expedient", meaning: "權宜之計 / 有利的", pos: "adj" },
    { word: "felicitous", meaning: "恰當的 / 幸福的", pos: "adj" },
    { word: "assiduous", meaning: "勤勉的 / 專心的", pos: "adj" },
    { word: "candor", meaning: "坦率 / 坦誠", pos: "n" },
    { word: "impute", meaning: "歸咎於 / 歸因於", pos: "v" },
    { word: "atrophy", meaning: "萎縮 / 衰退", pos: "n" },
    { word: "furtive", meaning: "偷偷摸摸的", pos: "adj" },
    { word: "exemplary", meaning: "典範的", pos: "adj" },
    { word: "ersatz", meaning: "代用的 / 假的", pos: "adj" }
  ],
  12: [
    { word: "penury", meaning: "貧困", pos: "n" },
    { word: "epicure", meaning: "美食家 / 享樂主義者", pos: "n" },
    { word: "eidolon", meaning: "幻影 / 理想", pos: "n" },
    { word: "evince", meaning: "表明 / 顯示", pos: "v" },
    { word: "effrontery", meaning: "厚顏無恥", pos: "n" },
    { word: "epigone", meaning: "平庸的追隨者 / 模仿者", pos: "n" },
    { word: "ostensible", meaning: "表面的 / 假裝的", pos: "adj" },
    { word: "banal", meaning: "陳腐的 / 平庸的", pos: "adj" },
    { word: "intrepid", meaning: "無畏的", pos: "adj" },
    { word: "irascible", meaning: "易怒的", pos: "adj" },
    { word: "exuberant", meaning: "繁茂的 / 熱情的", pos: "adj" },
    { word: "aporia", meaning: "困惑 / 難題", pos: "n" },
    { word: "conation", meaning: "意向 / 衝動", pos: "n" },
    { word: "cicatrize", meaning: "結痂 / 癒合", pos: "v" },
    { word: "semaphore", meaning: "臂板信號 / 信號標", pos: "n" },
    { word: "invective", meaning: "辱罵 / 抨擊", pos: "n" },
    { word: "misanthrope", meaning: "憤世嫉俗者", pos: "n" },
    { word: "meretricious", meaning: "俗氣的 / 華而不實的", pos: "adj" },
    { word: "mercurial", meaning: "反覆無常的 / 活潑的", pos: "adj" },
    { word: "imperturbable", meaning: "冷靜的 / 不受干擾的", pos: "adj" },
    { word: "putrefy", meaning: "腐爛", pos: "v" },
    { word: "fervor", meaning: "熱情 / 狂熱", pos: "n" },
    { word: "haughty", meaning: "傲慢的", pos: "adj" },
    { word: "recluse", meaning: "隱士", pos: "n" },
    { word: "truculent", meaning: "好鬥的 / 殘暴的", pos: "adj" },
    { word: "abeyance", meaning: "中止 / 擱置", pos: "n" },
    { word: "covenant", meaning: "契約 / 盟約", pos: "n" },
    { word: "ameliorate", meaning: "改善 / 改進", pos: "v" },
    { word: "squalid", meaning: "骯髒的", pos: "adj" },
    { word: "morose", meaning: "悶悶不樂的 / 憂鬱的", pos: "adj" }
  ],
  13: [
    { word: "surreptitious", meaning: "秘密的 / 鬼鬼祟祟的", pos: "adj" },
    { word: "oleaginous", meaning: "油腔滑調的 / 油膩的", pos: "adj" },
    { word: "maladroit", meaning: "笨拙的", pos: "adj" },
    { word: "bromidic", meaning: "平庸的 / 陳腐的", pos: "adj" },
    { word: "enthrall", meaning: "迷住 / 使神魂顛倒", pos: "v" },
    { word: "lethargy", meaning: "昏睡", pos: "n" },
    { word: "upbraid", meaning: "責備 / 譴責", pos: "v" },
    { word: "beguile", meaning: "欺騙 / 迷住", pos: "v" },
    { word: "caitiff", meaning: "膽小鬼 / 惡棍", pos: "n" },
    { word: "impecunious", meaning: "貧窮的 / 一文不名的", pos: "adj" },
    { word: "homiletic", meaning: "說教的", pos: "adj" },
    { word: "rebarbative", meaning: "令人討厭的 / 惹人反感的", pos: "adj" },
    { word: "penchant", meaning: "愛好 / 傾向", pos: "n" },
    { word: "astringent", meaning: "收斂的 / 嚴厲的", pos: "adj" },
    { word: "pavonine", meaning: "像孔雀的 / 絢麗的", pos: "adj" },
    { word: "modicum", meaning: "少量 / 一點點", pos: "n" },
    { word: "captious", meaning: "吹毛求疵的", pos: "adj" },
    { word: "inundate", meaning: "淹沒", pos: "v" },
    { word: "alias", meaning: "別名 / 化名", pos: "n" },
    { word: "recondite", meaning: "深奧的", pos: "adj" },
    { word: "insignia", meaning: "徽章", pos: "n" },
    { word: "stringent", meaning: "嚴格的 / 嚴厲的", pos: "adj" },
    { word: "vicarious", meaning: "替代的 / 間接體驗的", pos: "adj" },
    { word: "florid", meaning: "華麗的 / 紅潤的", pos: "adj" },
    { word: "rotundity", meaning: "圓胖", pos: "n" },
    { word: "gaudy", meaning: "俗艷的", pos: "adj" },
    { word: "empyrean", meaning: "最高天", pos: "n" },
    { word: "ambagious", meaning: "迂迴的 / 囉嗦的", pos: "adj" },
    { word: "precipitate", meaning: "促成", pos: "v" },
    { word: "pusillanimous", meaning: "懦弱的", pos: "adj" }
  ],
  14: [
    { word: "maudlin", meaning: "感情脆弱的 / 容易流淚的", pos: "adj" },
    { word: "concupiscence", meaning: "強烈的慾望 / 貪慾", pos: "n" },
    { word: "laudable", meaning: "值得讚賞的", pos: "adj" },
    { word: "daedal", meaning: "精巧的 / 錯綜複雜的", pos: "adj" },
    { word: "extol", meaning: "讚美 / 頌揚", pos: "v" },
    { word: "sciolism", meaning: "一知半解", pos: "n" },
    { word: "nudiustertian", meaning: "前天的", pos: "adj" },
    { word: "onerous", meaning: "繁重的 / 麻煩的", pos: "adj" },
    { word: "equine", meaning: "馬的", pos: "adj" },
    { word: "eulogy", meaning: "頌詞 / 悼詞", pos: "n" },
    { word: "celerity", meaning: "迅速 / 敏捷", pos: "n" },
    { word: "flagellate", meaning: "鞭打", pos: "v" },
    { word: "bathos", meaning: "突降法 / 令人發笑的頓挫", pos: "n" },
    { word: "assuetude", meaning: "習慣 / 慣例", pos: "n" },
    { word: "zenith", meaning: "頂點", pos: "n" },
    { word: "exalt", meaning: "讚揚 / 提拔", pos: "v" },
    { word: "obsequious", meaning: "諂媚的 / 奉承的", pos: "adj" },
    { word: "esurient", meaning: "飢餓的 / 貪婪的", pos: "adj" },
    { word: "effluence", meaning: "流出 / 散發", pos: "n" },
    { word: "distraught", meaning: "心煩意亂的 / 發狂的", pos: "adj" },
    { word: "prodigality", meaning: "揮霍", pos: "n" },
    { word: "indict", meaning: "起訴", pos: "v" },
    { word: "proclivity", meaning: "傾向 / 癖性", pos: "n" },
    { word: "bucolic", meaning: "田園風光的 / 鄉村的", pos: "adj" },
    { word: "legerdemain", meaning: "戲法 / 騙術", pos: "n" },
    { word: "virtuoso", meaning: "藝術大師 / 名家", pos: "n" },
    { word: "torpid", meaning: "遲鈍的 / 懶散的", pos: "adj" },
    { word: "compunction", meaning: "內疚 / 悔恨", pos: "n" },
    { word: "nefarious", meaning: "邪惡的 / 窮凶極惡的", pos: "adj" },
    { word: "canard", meaning: "謠言 / 誤傳", pos: "n" }
  ],
  15: [
    { word: "elixir", meaning: "靈丹妙藥 / 長生不老藥", pos: "n" },
    { word: "officious", meaning: "多管閒事的 / 愛發號施令的", pos: "adj" },
    { word: "abecedarian", meaning: "初學者的 / 字母的", pos: "adj" },
    { word: "venerable", meaning: "值得尊敬的", pos: "adj" },
    { word: "opprobrium", meaning: "恥辱", pos: "n" },
    { word: "loll", meaning: "懶散地坐", pos: "v" },
    { word: "anchorite", meaning: "隱士 / 隱修者", pos: "n" },
    { word: "temerity", meaning: "魯莽 / 冒失", pos: "n" },
    { word: "effete", meaning: "衰落的 / 疲憊的", pos: "adj" },
    { word: "ascetic", meaning: "苦行的 / 禁慾的", pos: "adj" },
    { word: "apostasy", meaning: "背教 / 變節", pos: "n" },
    { word: "approbate", meaning: "認可 / 贊同", pos: "v" },
    { word: "emissary", meaning: "使者", pos: "n" },
    { word: "foment", meaning: "煽動 / 挑起", pos: "v" },
    { word: "deference", meaning: "尊重", pos: "n" },
    { word: "histrionic", meaning: "戲劇的 / 裝腔作勢的", pos: "adj" },
    { word: "labile", meaning: "不穩定的 / 易變的", pos: "adj" },
    { word: "imbroglio", meaning: "紛爭 / 糾葛", pos: "n" },
    { word: "assuage", meaning: "緩和 / 減輕", pos: "v" },
    { word: "exegesis", meaning: "註釋 / 解釋", pos: "n" },
    { word: "corollary", meaning: "必然的結果 / 推論", pos: "n" },
    { word: "rescind", meaning: "廢除 / 取消", pos: "v" },
    { word: "dishabille", meaning: "衣衫不整", pos: "n" },
    { word: "olfactory", meaning: "嗅覺的", pos: "adj" },
    { word: "incondite", meaning: "粗糙的 / 未經修飾的", pos: "adj" },
    { word: "garrulous", meaning: "喋喋不休的", pos: "adj" },
    { word: "enigma", meaning: "謎", pos: "n" },
    { word: "fuliginous", meaning: "煤煙的 / 昏暗的", pos: "adj" },
    { word: "insipid", meaning: "乏味的 / 清淡的", pos: "adj" },
    { word: "despot", meaning: "專制君主 / 暴君", pos: "n" }
  ],
  16: [
    { word: "adumbrate", meaning: "預示 / 畫輪廓", pos: "v" },
    { word: "verbose", meaning: "囉嗦的 / 冗長的", pos: "adj" },
    { word: "inquisitive", meaning: "好奇的", pos: "adj" },
    { word: "remorse", meaning: "懊悔", pos: "n" },
    { word: "objurgate", meaning: "嚴責", pos: "v" },
    { word: "opalescent", meaning: "乳白的", pos: "adj" },
    { word: "apposite", meaning: "適當的 / 貼切的", pos: "adj" },
    { word: "inimical", meaning: "敵對的 / 有害的", pos: "adj" },
    { word: "malinger", meaning: "裝病 (以逃避工作)", pos: "v" },
    { word: "flout", meaning: "蔑視 / 嘲笑", pos: "v" },
    { word: "oculist", meaning: "眼科醫生", pos: "n" },
    { word: "guile", meaning: "狡詐", pos: "n" },
    { word: "pernicious", meaning: "有害的 / 致命的", pos: "adj" },
    { word: "orifice", meaning: "孔", pos: "n" },
    { word: "eigne", meaning: "長子繼承的", pos: "adj" },
    { word: "billet", meaning: "兵營 / 職位", pos: "n" },
    { word: "omphalos", meaning: "中心 / 肚臍", pos: "n" },
    { word: "attrition", meaning: "消耗 / 摩擦", pos: "n" },
    { word: "eremitic", meaning: "隱士的 / 隱居的", pos: "adj" },
    { word: "myopic", meaning: "目光短淺的 / 近視的", pos: "adj" },
    { word: "apprise", meaning: "通知 / 告知", pos: "v" },
    { word: "inveigle", meaning: "誘騙 / 誘使", pos: "v" },
    { word: "piety", meaning: "虔誠", pos: "n" },
    { word: "complaisant", meaning: "順從的 / 殷勤的", pos: "adj" },
    { word: "flagrant", meaning: "明目張膽的 / 惡名昭彰的", pos: "adj" },
    { word: "injunction", meaning: "命令 / 禁令", pos: "n" },
    { word: "apocryphal", meaning: "偽造的 / 虛構的", pos: "adj" },
    { word: "belie", meaning: "掩飾 / 與...不符", pos: "v" },
    { word: "demagogue", meaning: "煽動者 / 蠱惑民心的政客", pos: "n" },
    { word: "fracas", meaning: "吵鬧", pos: "n" }
  ]
};

export function getTotalRounds(): number {
  return Object.keys(wordSets).length;
}

export function getWordSet(round: number): Word[] {
  return wordSets[round] || [];
}
