export interface Word {
  word: string;
  meaning: string;
  pos: string; // Part of speech
}

export const wordSets: Record<number, Word[]> = {
  1: [
    { word: "incontrovertible", meaning: "無可辯駁的 / 不容置疑的", pos: "adj" },
    { word: "nondescript", meaning: "無特徵的", pos: "adj" },
    { word: "objurgation", meaning: "斥責", pos: "n" },
    { word: "malevolent", meaning: "有惡意的", pos: "adj" },
    { word: "malingerer", meaning: "裝病者", pos: "n" },
    { word: "ebullient", meaning: "熱情洋溢的 / 沸騰的", pos: "adj" },
    { word: "egregious", meaning: "極壞的 / 令人震驚的", pos: "adj" },
    { word: "petulance", meaning: "任性", pos: "n" },
    { word: "plaintiff", meaning: "原告", pos: "n" },
    { word: "gourmand", meaning: "貪吃者 / 饕客", pos: "n" },
    { word: "gullible", meaning: "易受騙的", pos: "adj" },
    { word: "brittle", meaning: "易碎的", pos: "adj" },
    { word: "burgeon", meaning: "萌芽 / 蓬勃發展", pos: "v" },
    { word: "polemic", meaning: "爭論", pos: "n" },
    { word: "portent", meaning: "預兆 / 凶兆", pos: "n" },
    { word: "fickle", meaning: "善變的", pos: "adj" },
    { word: "fidget", meaning: "坐立不安", pos: "v" },
    { word: "dirge", meaning: "輓歌 / 哀樂", pos: "n" },
    { word: "edict", meaning: "法令 / 佈告", pos: "n" },
    { word: "din", meaning: "喧囂", pos: "n" }
  ],
  2: [
    { word: "circumlocution", meaning: "迂迴的說法 / 累贅的陳述", pos: "n" },
    { word: "mollycoddle", meaning: "溺愛", pos: "v" },
    { word: "odoriferous", meaning: "有氣味的", pos: "adj" },
    { word: "lugubrious", meaning: "憂鬱的", pos: "adj" },
    { word: "mendacious", meaning: "虛假的 / 說謊的", pos: "adj" },
    { word: "duplicity", meaning: "口是心非 / 欺騙", pos: "n" },
    { word: "eloquence", meaning: "雄辯", pos: "n" },
    { word: "penurious", meaning: "吝嗇的 / 貧窮的", pos: "adj" },
    { word: "plaintive", meaning: "哀怨的", pos: "adj" },
    { word: "gossamer", meaning: "蛛絲 / 輕薄的", pos: "n" },
    { word: "harangue", meaning: "長篇大論", pos: "n" },
    { word: "boorish", meaning: "粗魯的 / 笨拙的", pos: "adj" },
    { word: "burnish", meaning: "擦亮 / 磨光", pos: "v" },
    { word: "plaudit", meaning: "喝采 / 讚賞", pos: "n" },
    { word: "presage", meaning: "預示 / 預兆", pos: "v" },
    { word: "fetter", meaning: "束縛 / 腳鐐", pos: "v" },
    { word: "flaunt", meaning: "炫耀", pos: "v" },
    { word: "demur", meaning: "反對", pos: "v" },
    { word: "elegy", meaning: "輓歌 / 哀歌", pos: "n" },
    { word: "yoke", meaning: "結合 / 束縛", pos: "v" }
  ],
  3: [
    { word: "predisposition", meaning: "傾向", pos: "n" },
    { word: "misanthrope", meaning: "厭世者", pos: "n" },
    { word: "opprobrious", meaning: "辱罵的", pos: "adj" },
    { word: "loquacious", meaning: "多嘴的", pos: "adj" },
    { word: "meticulous", meaning: "一絲不苟的", pos: "adj" },
    { word: "dumbfound", meaning: "使驚呆", pos: "v" },
    { word: "embellish", meaning: "裝飾", pos: "v" },
    { word: "parquetry", meaning: "鑲木地板", pos: "n" },
    { word: "platitude", meaning: "老生常談 / 陳詞濫調", pos: "n" },
    { word: "glabrous", meaning: "光滑無毛的", pos: "adj" },
    { word: "hegemony", meaning: "霸權 / 領導權", pos: "n" },
    { word: "beguile", meaning: "欺騙 / 迷住", pos: "v" },
    { word: "callous", meaning: "冷酷無情的 / 麻木的", pos: "adj" },
    { word: "placate", meaning: "安撫", pos: "v" },
    { word: "probity", meaning: "誠實 / 正直", pos: "n" },
    { word: "fervor", meaning: "熱情", pos: "n" },
    { word: "flimsy", meaning: "脆弱的", pos: "adj" },
    { word: "decry", meaning: "譴責", pos: "v" },
    { word: "ethos", meaning: "民族精神", pos: "n" },
    { word: "wily", meaning: "狡猾的 / 詭計多端的", pos: "adj" }
  ],
  4: [
    { word: "quintessential", meaning: "精髓的", pos: "adj" },
    { word: "metaphysics", meaning: "形而上學", pos: "n" },
    { word: "optometrist", meaning: "驗光師", pos: "n" },
    { word: "licentious", meaning: "放蕩的 / 淫亂的", pos: "adj" },
    { word: "mettlesome", meaning: "有勇氣的", pos: "adj" },
    { word: "disrepute", meaning: "聲名狼藉 / 壞名聲", pos: "n" },
    { word: "emollient", meaning: "潤膚劑 / 緩和的", pos: "adj" },
    { word: "panegyric", meaning: "頌詞", pos: "n" },
    { word: "ponderous", meaning: "笨重的", pos: "adj" },
    { word: "flounder", meaning: "掙扎", pos: "v" },
    { word: "impudent", meaning: "無禮的", pos: "adj" },
    { word: "bashful", meaning: "害羞的 / 羞怯的", pos: "adj" },
    { word: "calumny", meaning: "誹謗 / 誣衊", pos: "n" },
    { word: "piquant", meaning: "辛辣的", pos: "adj" },
    { word: "protean", meaning: "千變萬化的 / 多變的", pos: "adj" },
    { word: "fervid", meaning: "熱情的", pos: "adj" },
    { word: "flinch", meaning: "畏縮", pos: "v" },
    { word: "daunt", meaning: "使畏縮 / 恐嚇", pos: "v" },
    { word: "extol", meaning: "讚美 / 頌揚", pos: "v" },
    { word: "wile", meaning: "詭計", pos: "n" }
  ],
  5: [
    { word: "anachronistic", meaning: "時代錯誤的 / 過時的", pos: "adj" },
    { word: "mellifluous", meaning: "甜美的 / 流暢的", pos: "adj" },
    { word: "ornithology", meaning: "鳥類學", pos: "n" },
    { word: "lachrymose", meaning: "愛哭的 / 催人淚下的", pos: "adj" },
    { word: "munificent", meaning: "慷慨的 / 豐厚的", pos: "adj" },
    { word: "disparity", meaning: "差異", pos: "n" },
    { word: "equivocal", meaning: "模稜兩可的 / 含糊的", pos: "adj" },
    { word: "ostracize", meaning: "排斥", pos: "v" },
    { word: "potentate", meaning: "統治者 / 君主", pos: "n" },
    { word: "flippant", meaning: "輕率的", pos: "adj" },
    { word: "impunity", meaning: "免受懲罰", pos: "n" },
    { word: "avarice", meaning: "貪婪", pos: "n" },
    { word: "caprice", meaning: "反覆無常", pos: "n" },
    { word: "pillage", meaning: "掠奪", pos: "v" },
    { word: "prudent", meaning: "謹慎的", pos: "adj" },
    { word: "fathom", meaning: "領會 / 英尋", pos: "v" },
    { word: "florid", meaning: "華麗的", pos: "adj" },
    { word: "crave", meaning: "渴望", pos: "v" },
    { word: "feign", meaning: "假裝", pos: "v" },
    { word: "tout", meaning: "兜售", pos: "v" }
  ],
  6: [
    { word: "conflagration", meaning: "大火 / 戰火", pos: "n" },
    { word: "malapropism", meaning: "文字誤用", pos: "n" },
    { word: "orthography", meaning: "正字法", pos: "n" },
    { word: "invigorate", meaning: "鼓舞", pos: "v" },
    { word: "obsequious", meaning: "諂媚的", pos: "adj" },
    { word: "discourse", meaning: "演講 / 論述", pos: "n" },
    { word: "eradicate", meaning: "根除", pos: "v" },
    { word: "ostracism", meaning: "排斥 / 放逐", pos: "n" },
    { word: "precipice", meaning: "懸崖", pos: "n" },
    { word: "flagrant", meaning: "明目張膽的 / 惡名昭彰的", pos: "adj" },
    { word: "inchoate", meaning: "早期的 / 未成形的", pos: "adj" },
    { word: "austere", meaning: "嚴厲的 / 簡樸的", pos: "adj" },
    { word: "carouse", meaning: "狂歡 / 痛飲", pos: "v" },
    { word: "perfidy", meaning: "不忠", pos: "n" },
    { word: "puerile", meaning: "幼稚的 / 孩童的", pos: "adj" },
    { word: "falter", meaning: "蹣跚 / 猶豫", pos: "v" },
    { word: "foible", meaning: "小缺點", pos: "n" },
    { word: "cower", meaning: "畏縮", pos: "v" },
    { word: "flout", meaning: "蔑視", pos: "v" },
    { word: "tome", meaning: "大部頭書 / 巨著", pos: "n" }
  ],
  7: [
    { word: "consternation", meaning: "驚愕", pos: "n" },
    { word: "magnanimity", meaning: "寬宏大量", pos: "n" },
    { word: "panglossian", meaning: "盲目樂觀的", pos: "adj" },
    { word: "inveterate", meaning: "根深蒂固的 / 積習的", pos: "adj" },
    { word: "omnivorous", meaning: "雜食性的", pos: "adj" },
    { word: "discomfit", meaning: "使窘迫 / 挫敗", pos: "v" },
    { word: "euphemism", meaning: "委婉語", pos: "n" },
    { word: "opportune", meaning: "適時的", pos: "adj" },
    { word: "proscribe", meaning: "禁止 / 放逐", pos: "v" },
    { word: "feckless", meaning: "無能的", pos: "adj" },
    { word: "inimical", meaning: "敵意的 / 有害的", pos: "adj" },
    { word: "atrophy", meaning: "萎縮 / 退化", pos: "v" },
    { word: "caustic", meaning: "腐蝕性的 / 尖刻的", pos: "adj" },
    { word: "paucity", meaning: "缺乏 / 稀少", pos: "n" },
    { word: "pungent", meaning: "辛辣的", pos: "adj" },
    { word: "exhort", meaning: "勸告 / 勉勵", pos: "v" },
    { word: "foment", meaning: "煽動", pos: "v" },
    { word: "chary", meaning: "謹慎的", pos: "adj" },
    { word: "frown", meaning: "皺眉", pos: "v" },
    { word: "rife", meaning: "充斥的 / 普遍的", pos: "adj" }
  ],
  8: [
    { word: "controversial", meaning: "有爭議的", pos: "adj" },
    { word: "legerdemain", meaning: "戲法 / 騙術", pos: "n" },
    { word: "perfunctory", meaning: "敷衍的", pos: "adj" },
    { word: "intimation", meaning: "暗示 / 透露", pos: "n" },
    { word: "opalescent", meaning: "乳白的", pos: "adj" },
    { word: "diffident", meaning: "羞怯的", pos: "adj" },
    { word: "exculpate", meaning: "證明無罪", pos: "v" },
    { word: "oligarchy", meaning: "寡頭政治", pos: "n" },
    { word: "querulous", meaning: "愛抱怨的 / 易怒的", pos: "adj" },
    { word: "esurient", meaning: "飢餓的 / 貪婪的", pos: "adj" },
    { word: "insignia", meaning: "徽章", pos: "n" },
    { word: "assuage", meaning: "緩和 / 減輕", pos: "v" },
    { word: "cobbler", meaning: "鞋匠", pos: "n" },
    { word: "orotund", meaning: "響亮的", pos: "adj" },
    { word: "putrefy", meaning: "腐爛", pos: "v" },
    { word: "evince", meaning: "表明 / 顯示", pos: "v" },
    { word: "fracas", meaning: "吵鬧", pos: "n" },
    { word: "brood", meaning: "沉思 / 籠罩", pos: "v" },
    { word: "gaffe", meaning: "失禮", pos: "n" },
    { word: "pert", meaning: "俏皮的 / 魯莽的", pos: "adj" }
  ],
  9: [
    { word: "dispassionate", meaning: "冷靜的", pos: "adj" },
    { word: "irreverence", meaning: "不敬 / 輕蔑", pos: "n" },
    { word: "precipitate", meaning: "促成", pos: "v" },
    { word: "insensible", meaning: "無知覺的", pos: "adj" },
    { word: "opprobrium", meaning: "恥辱", pos: "n" },
    { word: "dichotomy", meaning: "二分法", pos: "n" },
    { word: "execrable", meaning: "劣等的 / 該咒罵的", pos: "adj" },
    { word: "olfactory", meaning: "嗅覺的", pos: "adj" },
    { word: "quotidian", meaning: "每日的", pos: "adj" },
    { word: "esoteric", meaning: "深奧的", pos: "adj" },
    { word: "intrepid", meaning: "無畏的", pos: "adj" },
    { word: "ascetic", meaning: "苦行的 / 禁慾的", pos: "adj" },
    { word: "conceit", meaning: "自負", pos: "n" },
    { word: "orifice", meaning: "孔", pos: "n" },
    { word: "quibble", meaning: "狡辯", pos: "v" },
    { word: "eschew", meaning: "避開", pos: "v" },
    { word: "frenzy", meaning: "瘋狂", pos: "n" },
    { word: "brisk", meaning: "輕快的", pos: "adj" },
    { word: "gaudy", meaning: "俗艷的", pos: "adj" },
    { word: "ogle", meaning: "拋媚眼", pos: "v" }
  ],
  10: [
    { word: "grandiloquent", meaning: "誇張的 / 浮誇的", pos: "adj" },
    { word: "interregnum", meaning: "過渡期", pos: "n" },
    { word: "precipitous", meaning: "險峻的", pos: "adj" },
    { word: "injunction", meaning: "命令 / 禁令", pos: "n" },
    { word: "ostensible", meaning: "表面的 / 假裝的", pos: "adj" },
    { word: "desultory", meaning: "漫無目的的 / 散漫的", pos: "adj" },
    { word: "exemplary", meaning: "典範的", pos: "adj" },
    { word: "officious", meaning: "多管閒事的 / 愛發號施令的", pos: "adj" },
    { word: "recondite", meaning: "深奧的", pos: "adj" },
    { word: "enervate", meaning: "使衰弱 / 使失去活力", pos: "v" },
    { word: "inundate", meaning: "淹沒", pos: "v" },
    { word: "artless", meaning: "天真的 / 樸實的", pos: "adj" },
    { word: "concoct", meaning: "調製 / 編造", pos: "v" },
    { word: "onerous", meaning: "繁重的 / 麻煩的", pos: "adj" },
    { word: "recluse", meaning: "隱士", pos: "n" },
    { word: "equine", meaning: "馬的", pos: "adj" },
    { word: "gauche", meaning: "笨拙的", pos: "adj" },
    { word: "belie", meaning: "掩飾 / 與...不符", pos: "v" },
    { word: "gavel", meaning: "小槌", pos: "n" },
    { word: "molt", meaning: "脫毛", pos: "v" }
  ],
  11: [
    { word: "idiosyncratic", meaning: "特質的 / 獨特的", pos: "adj" },
    { word: "inquisitive", meaning: "好奇的", pos: "adj" },
    { word: "prerogative", meaning: "特權", pos: "n" },
    { word: "iniquitous", meaning: "極不公正的", pos: "adj" },
    { word: "peccadillo", meaning: "小過失", pos: "n" },
    { word: "desiccate", meaning: "使脫水", pos: "v" },
    { word: "exonerate", meaning: "證明無罪", pos: "v" },
    { word: "obtrusive", meaning: "冒失的", pos: "adj" },
    { word: "reprobate", meaning: "墮落者 / 惡棍", pos: "n" },
    { word: "encumber", meaning: "阻礙", pos: "v" },
    { word: "largesse", meaning: "慷慨 / 恩賜", pos: "n" },
    { word: "apprise", meaning: "通知 / 告知", pos: "v" },
    { word: "condone", meaning: "寬恕 / 赦免", pos: "v" },
    { word: "odorous", meaning: "有香味的", pos: "adj" },
    { word: "remorse", meaning: "懊悔", pos: "n" },
    { word: "ensign", meaning: "艦隊旗 / 少尉", pos: "n" },
    { word: "gravel", meaning: "碎石", pos: "n" },
    { word: "banal", meaning: "陳腐的 / 平庸的", pos: "adj" },
    { word: "gloat", meaning: "幸災樂禍", pos: "v" },
    { word: "moat", meaning: "護城河", pos: "n" }
  ],
  12: [
    { word: "perspicacious", meaning: "敏銳的 / 有洞察力的", pos: "adj" },
    { word: "inopportune", meaning: "不合時宜的", pos: "adj" },
    { word: "prevaricate", meaning: "支吾其詞", pos: "v" },
    { word: "infiltrate", meaning: "滲透", pos: "v" },
    { word: "pejorative", meaning: "貶義的 / 輕蔑的", pos: "adj" },
    { word: "denigrate", meaning: "貶低 / 詆毀", pos: "v" },
    { word: "expedient", meaning: "權宜之計 / 有利的", pos: "adj" },
    { word: "objurgate", meaning: "嚴責", pos: "v" },
    { word: "rotundity", meaning: "圓胖", pos: "n" },
    { word: "encroach", meaning: "侵佔", pos: "v" },
    { word: "laudable", meaning: "值得讚賞的", pos: "adj" },
    { word: "adamant", meaning: "堅決的 / 固執的", pos: "adj" },
    { word: "conduit", meaning: "導管 / 管道", pos: "n" },
    { word: "oculist", meaning: "眼科醫生", pos: "n" },
    { word: "rescind", meaning: "廢除 / 取消", pos: "v" },
    { word: "enlist", meaning: "徵募", pos: "v" },
    { word: "grovel", meaning: "卑躬屈膝", pos: "v" },
    { word: "ardor", meaning: "熱情 / 熱心", pos: "n" },
    { word: "guile", meaning: "狡詐", pos: "n" },
    { word: "mace", meaning: "權杖", pos: "n" }
  ],
  13: [
    { word: "preponderance", meaning: "優勢 / 多數", pos: "n" },
    { word: "inflammable", meaning: "易燃的", pos: "adj" },
    { word: "prodigality", meaning: "揮霍", pos: "n" },
    { word: "inexorable", meaning: "不可阻擋的 / 無情的", pos: "adj" },
    { word: "peremptory", meaning: "專橫的", pos: "adj" },
    { word: "demagogue", meaning: "煽動者 / 蠱惑民心的政客", pos: "n" },
    { word: "expurgate", meaning: "刪除（不當內容） / 淨化", pos: "v" },
    { word: "obfuscate", meaning: "使模糊 / 使困惑", pos: "v" },
    { word: "saturnine", meaning: "憂鬱的", pos: "adj" },
    { word: "encomium", meaning: "讚美", pos: "n" },
    { word: "lethargy", meaning: "昏睡", pos: "n" },
    { word: "acerbic", meaning: "尖刻的 / 苦澀的", pos: "adj" },
    { word: "conifer", meaning: "針葉樹", pos: "n" },
    { word: "obviate", meaning: "排除", pos: "v" },
    { word: "squalid", meaning: "骯髒的", pos: "adj" },
    { word: "enigma", meaning: "謎", pos: "n" },
    { word: "imbibe", meaning: "飲 / 吸收", pos: "v" },
    { word: "annex", meaning: "附加 / 併吞", pos: "v" },
    { word: "imbue", meaning: "灌輸", pos: "v" },
    { word: "lull", meaning: "使平靜", pos: "v" }
  ],
  14: [
    { word: "pusillanimous", meaning: "懦弱的", pos: "adj" },
    { word: "incongruous", meaning: "不協調的", pos: "adj" },
    { word: "pulchritude", meaning: "美麗 / 標緻", pos: "n" },
    { word: "impervious", meaning: "不受影響的", pos: "adj" },
    { word: "perfidious", meaning: "不忠的", pos: "adj" },
    { word: "delineate", meaning: "描繪", pos: "v" },
    { word: "extempore", meaning: "即席的", pos: "adj" },
    { word: "obeisance", meaning: "敬禮", pos: "n" },
    { word: "semaphore", meaning: "臂板信號 / 信號標", pos: "n" },
    { word: "empyrean", meaning: "最高天", pos: "n" },
    { word: "ligneous", meaning: "木質的", pos: "adj" },
    { word: "abscond", meaning: "潛逃 / 逃跑", pos: "v" },
    { word: "conjure", meaning: "變戲法 / 召喚", pos: "v" },
    { word: "obtrude", meaning: "強加", pos: "v" },
    { word: "squelch", meaning: "壓制", pos: "v" },
    { word: "elicit", meaning: "引出 / 探出", pos: "v" },
    { word: "impugn", meaning: "責難", pos: "v" },
    { word: "alias", meaning: "別名 / 化名", pos: "n" },
    { word: "inane", meaning: "空洞的 / 愚蠢的", pos: "adj" },
    { word: "lope", meaning: "大步慢跑", pos: "v" }
  ],
  15: [
    { word: "sanctimonious", meaning: "假裝虔誠的 / 偽善的", pos: "adj" },
    { word: "impregnable", meaning: "堅不可摧的", pos: "adj" },
    { word: "punctilious", meaning: "一絲不苟的 / 拘泥細節的", pos: "adj" },
    { word: "imperative", meaning: "必要的", pos: "adj" },
    { word: "pernicious", meaning: "有害的 / 致命的", pos: "adj" },
    { word: "deference", meaning: "尊重", pos: "n" },
    { word: "extensive", meaning: "廣泛的", pos: "adj" },
    { word: "nonplused", meaning: "困惑的", pos: "adj" },
    { word: "solipsism", meaning: "唯我論", pos: "n" },
    { word: "emissary", meaning: "使者", pos: "n" },
    { word: "linchpin", meaning: "關鍵人物 / 樞紐", pos: "n" },
    { word: "virtuoso", meaning: "藝術大師 / 名家", pos: "n" },
    { word: "connive", meaning: "縱容 / 默許", pos: "v" },
    { word: "obloquy", meaning: "辱罵", pos: "n" },
    { word: "stifled", meaning: "窒息的", pos: "adj" },
    { word: "efface", meaning: "抹去", pos: "v" },
    { word: "impute", meaning: "歸咎於 / 歸因於", pos: "v" },
    { word: "zephyr", meaning: "微風 / 和風", pos: "n" },
    { word: "inure", meaning: "使習慣於 / 生效", pos: "v" },
    { word: "loll", meaning: "懶散地坐", pos: "v" }
  ],
  16: [
    { word: "surreptitious", meaning: "秘密的 / 鬼鬼祟祟的", pos: "adj" },
    { word: "impecunious", meaning: "貧窮的 / 一文不名的", pos: "adj" },
    { word: "rebarbative", meaning: "令人討厭的 / 惹人反感的", pos: "adj" },
    { word: "idolatrous", meaning: "盲目崇拜的", pos: "adj" },
    { word: "pestilence", meaning: "瘟疫", pos: "n" },
    { word: "credulity", meaning: "輕信", pos: "n" },
    { word: "exuberant", meaning: "繁茂的 / 熱情的", pos: "adj" },
    { word: "nocturnal", meaning: "夜間的", pos: "adj" },
    { word: "subjugate", meaning: "征服 / 降伏", pos: "v" },
    { word: "eclectic", meaning: "折衷的 / 綜合的", pos: "adj" },
    { word: "litigant", meaning: "訴訟當事人", pos: "n" },
    { word: "verbiage", meaning: "冗詞", pos: "n" },
    { word: "consign", meaning: "委託 / 交付", pos: "v" },
    { word: "obelisk", meaning: "方尖碑", pos: "n" },
    { word: "striate", meaning: "加條紋", pos: "v" },
    { word: "duress", meaning: "脅迫 / 壓力", pos: "n" },
    { word: "indict", meaning: "起訴", pos: "v" },
    { word: "zenith", meaning: "頂點", pos: "n" },
    { word: "irate", meaning: "發怒的", pos: "adj" },
    { word: "jest", meaning: "笑話", pos: "n" }
  ],
  17: [
    { word: "adulteration", meaning: "摻雜", pos: "n" },
    { word: "hagiography", meaning: "聖徒傳記 / 捧場傳記", pos: "n" },
    { word: "redoubtable", meaning: "可怕的 / 令人敬畏的", pos: "adj" },
    { word: "iconoclast", meaning: "偶像破壞者 / 反傳統者", pos: "n" },
    { word: "phlegmatic", meaning: "冷靜的 / 遲鈍的", pos: "adj" },
    { word: "convivial", meaning: "歡樂的 / 友好的", pos: "adj" },
    { word: "facetious", meaning: "滑稽的", pos: "adj" },
    { word: "neuralgia", meaning: "神經痛", pos: "n" },
    { word: "sycophant", meaning: "諂媚者 / 拍馬屁的人", pos: "n" },
    { word: "dogmatic", meaning: "教條的 / 武斷的", pos: "adj" },
    { word: "luminous", meaning: "發光的", pos: "adj" },
    { word: "veracity", meaning: "誠實 / 真實", pos: "n" },
    { word: "convoke", meaning: "召集", pos: "v" },
    { word: "noisome", meaning: "惡臭的 / 有害的", pos: "adj" },
    { word: "surfeit", meaning: "過量 / 飲食過度", pos: "n" },
    { word: "docile", meaning: "溫順的", pos: "adj" },
    { word: "induce", meaning: "誘導", pos: "v" },
    { word: "zealot", meaning: "狂熱者", pos: "n" },
    { word: "jaded", meaning: "厭倦的 / 疲憊的", pos: "adj" },
    { word: "jamb", meaning: "門框", pos: "n" }
  ],
  18: [
    { word: "antediluvian", meaning: "史前的 / 陳舊的", pos: "adj" },
    { word: "foreclosure", meaning: "取消抵押品贖回權", pos: "n" },
    { word: "requisition", meaning: "徵用 / 需求", pos: "n" },
    { word: "herbaceous", meaning: "草本的", pos: "adj" },
    { word: "precarious", meaning: "不穩定的", pos: "adj" },
    { word: "contusion", meaning: "挫傷 / 瘀傷", pos: "n" },
    { word: "fanatical", meaning: "狂熱的", pos: "adj" },
    { word: "nefarious", meaning: "邪惡的", pos: "adj" },
    { word: "tantalize", meaning: "逗弄", pos: "v" },
    { word: "divisive", meaning: "引起分歧的 / 導致分裂的", pos: "adj" },
    { word: "lustrous", meaning: "有光澤的", pos: "adj" },
    { word: "venerate", meaning: "崇敬", pos: "v" },
    { word: "coterie", meaning: "小圈子 / 圈內人", pos: "n" },
    { word: "nascent", meaning: "初生的 / 萌芽的", pos: "adj" },
    { word: "swarthy", meaning: "黝黑的 / 黑皮膚的", pos: "adj" },
    { word: "dispel", meaning: "驅散 / 消除", pos: "v" },
    { word: "infuse", meaning: "注入", pos: "v" },
    { word: "wheeze", meaning: "喘息", pos: "v" },
    { word: "knell", meaning: "喪鐘聲 / 凶兆", pos: "n" },
    { word: "goad", meaning: "激勵 / 唆使", pos: "v" }
  ],
  19: [
    { word: "blandishment", meaning: "奉承 / 甜言蜜語", pos: "n" },
    { word: "forbearance", meaning: "忍耐 / 寬容", pos: "n" },
    { word: "susurration", meaning: "颯颯聲 / 竊竊私語", pos: "n" },
    { word: "gregarious", meaning: "群居的 / 愛社交的", pos: "adj" },
    { word: "precedence", meaning: "優先", pos: "n" },
    { word: "conscript", meaning: "徵兵", pos: "v" },
    { word: "fledgling", meaning: "雛鳥 / 新手", pos: "n" },
    { word: "minuscule", meaning: "極小的", pos: "adj" },
    { word: "temperate", meaning: "溫和的", pos: "adj" },
    { word: "dislodge", meaning: "逐出", pos: "v" },
    { word: "macerate", meaning: "浸軟", pos: "v" },
    { word: "uxorious", meaning: "溺愛妻子的", pos: "adj" },
    { word: "debauch", meaning: "墮落 / 放蕩", pos: "v" },
    { word: "mollify", meaning: "撫慰", pos: "v" },
    { word: "swindle", meaning: "詐騙", pos: "v" },
    { word: "devoid", meaning: "缺乏的", pos: "adj" },
    { word: "inured", meaning: "習慣了的", pos: "adj" },
    { word: "welter", meaning: "混亂", pos: "n" },
    { word: "lasso", meaning: "套索", pos: "n" },
    { word: "glib", meaning: "油腔滑調的", pos: "adj" }
  ],
  20: [
    { word: "circumscribe", meaning: "限制 / 畫界線", pos: "v" },
    { word: "enfranchise", meaning: "給予選舉權 / 解放", pos: "v" },
    { word: "treacherous", meaning: "背叛的", pos: "adj" },
    { word: "gratuitous", meaning: "無緣無故的 / 免費的", pos: "adj" },
    { word: "prescience", meaning: "先見之明", pos: "n" },
    { word: "congruity", meaning: "一致 / 適合", pos: "n" },
    { word: "foolhardy", meaning: "魯莽的", pos: "adj" },
    { word: "mercurial", meaning: "反覆無常的", pos: "adj" },
    { word: "tentative", meaning: "試驗性的", pos: "adj" },
    { word: "disburse", meaning: "支付", pos: "v" },
    { word: "martinet", meaning: "嚴格執行紀律的人", pos: "n" },
    { word: "travesty", meaning: "拙劣的模仿 / 嘲弄", pos: "n" },
    { word: "decorum", meaning: "禮節", pos: "n" },
    { word: "modicum", meaning: "少量 / 一點點", pos: "n" },
    { word: "tarnish", meaning: "敗壞", pos: "v" },
    { word: "despot", meaning: "專制君主 / 暴君", pos: "n" },
    { word: "jejune", meaning: "枯燥無味的 / 幼稚的", pos: "adj" },
    { word: "wanton", meaning: "肆無忌憚的 / 淫蕩的", pos: "adj" },
    { word: "leash", meaning: "皮帶", pos: "n" },
    { word: "fret", meaning: "煩躁", pos: "v" }
  ],
  21: [
    { word: "commensurate", meaning: "相稱的 / 同量的", pos: "adj" },
    { word: "egalitarian", meaning: "平等主義的", pos: "adj" },
    { word: "trepidation", meaning: "恐懼", pos: "n" },
    { word: "fortuitous", meaning: "偶然的 / 幸運的", pos: "adj" },
    { word: "proclivity", meaning: "傾向 / 癖性", pos: "n" },
    { word: "congruent", meaning: "一致的", pos: "adj" },
    { word: "forestall", meaning: "先發制人", pos: "v" },
    { word: "mercenary", meaning: "唯利是圖的", pos: "adj" },
    { word: "trenchant", meaning: "銳利的 / 一針見血的", pos: "adj" },
    { word: "diligent", meaning: "勤奮的", pos: "adj" },
    { word: "mediocre", meaning: "平庸的", pos: "adj" },
    { word: "taciturn", meaning: "沉默寡言的", pos: "adj" },
    { word: "defunct", meaning: "死亡的 / 廢止的", pos: "adj" },
    { word: "mawkish", meaning: "無病呻吟的 / 令人作嘔的", pos: "adj" },
    { word: "tenable", meaning: "站得住腳的", pos: "adj" },
    { word: "descry", meaning: "看見", pos: "v" },
    { word: "jovial", meaning: "愉快的", pos: "adj" },
    { word: "vilify", meaning: "誹謗 / 貶低", pos: "v" },
    { word: "levee", meaning: "河堤", pos: "n" },
    { word: "foil", meaning: "阻撓 / 挫敗", pos: "v" }
  ],
  22: [
    { word: "conciliatory", meaning: "調解的", pos: "adj" },
    { word: "efficacious", meaning: "有效的", pos: "adj" },
    { word: "unequivocal", meaning: "明確的", pos: "adj" },
    { word: "forthright", meaning: "直率的", pos: "adj" },
    { word: "prodigious", meaning: "巨大的", pos: "adj" },
    { word: "coagulate", meaning: "凝結", pos: "v" },
    { word: "fractious", meaning: "易怒的 / 倔強的", pos: "adj" },
    { word: "maelstrom", meaning: "大漩渦 / 大混亂", pos: "n" },
    { word: "truculent", meaning: "好鬥的 / 殘暴的", pos: "adj" },
    { word: "didactic", meaning: "說教的 / 教誨的", pos: "adj" },
    { word: "minatory", meaning: "威脅的 / 恫嚇的", pos: "adj" },
    { word: "subpoena", meaning: "傳票", pos: "n" },
    { word: "digress", meaning: "離題", pos: "v" },
    { word: "maudlin", meaning: "傷感的 / 容易流淚的", pos: "adj" },
    { word: "trample", meaning: "踐踏", pos: "v" },
    { word: "deride", meaning: "嘲笑 / 愚弄", pos: "v" },
    { word: "leaven", meaning: "發酵劑", pos: "n" },
    { word: "vagary", meaning: "奇想", pos: "n" },
    { word: "linen", meaning: "亞麻布", pos: "n" },
    { word: "feud", meaning: "世仇", pos: "n" }
  ],
  23: [
    { word: "confidential", meaning: "機密的", pos: "adj" },
    { word: "crepuscular", meaning: "黃昏的 / 朦朧的", pos: "adj" },
    { word: "vicissitude", meaning: "變遷 / 盛衰", pos: "n" },
    { word: "flamboyant", meaning: "炫耀的", pos: "adj" },
    { word: "profligate", meaning: "揮霍的 / 墮落的", pos: "adj" },
    { word: "coagulant", meaning: "凝結劑", pos: "n" },
    { word: "frivolous", meaning: "輕浮的", pos: "adj" },
    { word: "libertine", meaning: "放蕩者", pos: "n" },
    { word: "turpitude", meaning: "卑鄙 / 墮落", pos: "n" },
    { word: "diatribe", meaning: "抨擊", pos: "n" },
    { word: "misnomer", meaning: "誤稱", pos: "n" },
    { word: "stockade", meaning: "柵欄", pos: "n" },
    { word: "disdain", meaning: "蔑視", pos: "n" },
    { word: "macabre", meaning: "恐怖的 / 令人毛骨悚然的", pos: "adj" },
    { word: "umbrage", meaning: "生氣 / 怨恨", pos: "n" },
    { word: "demote", meaning: "降職", pos: "v" },
    { word: "loafer", meaning: "懶漢", pos: "n" },
    { word: "uproar", meaning: "騷動", pos: "n" },
    { word: "maxim", meaning: "格言 / 箴言", pos: "n" },
    { word: "fawn", meaning: "奉承 / 小鹿", pos: "v" }
  ],
  24: [
    { word: "contumacious", meaning: "拒不服從的 / 頑固抗拒的", pos: "adj" },
    { word: "corroborate", meaning: "證實", pos: "v" },
    { word: "aberration", meaning: "異常 / 偏差", pos: "n" },
    { word: "felicitate", meaning: "祝賀", pos: "v" },
    { word: "promulgate", meaning: "公布 / 頒布", pos: "v" },
    { word: "chicanery", meaning: "欺騙", pos: "n" },
    { word: "fulminate", meaning: "嚴厲譴責", pos: "v" },
    { word: "leviathan", meaning: "龐然大物", pos: "n" },
    { word: "untenable", meaning: "站不住腳的", pos: "adj" },
    { word: "defiance", meaning: "挑釁", pos: "n" },
    { word: "narcotic", meaning: "麻醉劑", pos: "n" },
    { word: "squander", meaning: "揮霍", pos: "v" },
    { word: "divulge", meaning: "洩露", pos: "v" },
    { word: "laconic", meaning: "簡潔的 / 寡言的", pos: "adj" },
    { word: "upbraid", meaning: "責罵 / 訓斥", pos: "v" },
    { word: "deluge", meaning: "洪水", pos: "n" },
    { word: "lumber", meaning: "木材", pos: "n" },
    { word: "tremor", meaning: "顫抖", pos: "n" },
    { word: "mirth", meaning: "歡笑", pos: "n" },
    { word: "espy", meaning: "窺見", pos: "v" }
  ],
  25: [
    { word: "defenestrate", meaning: "把某人扔出窗外 / 罷免", pos: "v" },
    { word: "constituent", meaning: "成分 / 選民", pos: "n" },
    { word: "abnegation", meaning: "拒絕 / 放棄", pos: "n" },
    { word: "fastidious", meaning: "挑剔的 / 難以取悅的", pos: "adj" },
    { word: "propitiate", meaning: "撫慰", pos: "v" },
    { word: "castigate", meaning: "嚴懲", pos: "v" },
    { word: "garrulous", meaning: "喋喋不休的 / 饒舌的", pos: "adj" },
    { word: "lethargic", meaning: "昏睡的", pos: "adj" },
    { word: "vacillate", meaning: "動搖", pos: "v" },
    { word: "decorous", meaning: "端莊的", pos: "adj" },
    { word: "neophyte", meaning: "新手 / 初學者", pos: "n" },
    { word: "spurious", meaning: "偽造的 / 欺騙的", pos: "adj" },
    { word: "doleful", meaning: "悲哀的", pos: "adj" },
    { word: "kinetic", meaning: "運動的 / 活躍的", pos: "adj" },
    { word: "verdant", meaning: "翠綠的", pos: "adj" },
    { word: "decree", meaning: "法令", pos: "n" },
    { word: "maggot", meaning: "蛆", pos: "n" },
    { word: "torpor", meaning: "麻木", pos: "n" },
    { word: "mores", meaning: "風俗 / 習慣", pos: "n" },
    { word: "dupe", meaning: "欺騙", pos: "v" }
  ],
  26: [
    { word: "eleemosynary", meaning: "慈善的 / 施捨的", pos: "adj" },
    { word: "connoisseur", meaning: "鑑賞家 / 行家", pos: "n" },
    { word: "abstemious", meaning: "有節制的 / 簡樸的", pos: "adj" },
    { word: "fallacious", meaning: "謬誤的 / 騙人的", pos: "adj" },
    { word: "protracted", meaning: "延長的", pos: "adj" },
    { word: "cacophony", meaning: "刺耳的聲音 / 雜音", pos: "n" },
    { word: "guileless", meaning: "厚道的", pos: "adj" },
    { word: "laudatory", meaning: "讚美的", pos: "adj" },
    { word: "vehemence", meaning: "激烈", pos: "n" },
    { word: "cynosure", meaning: "眾人矚目的焦點", pos: "n" },
    { word: "nugatory", meaning: "無價值的 / 無效的", pos: "adj" },
    { word: "sporadic", meaning: "零星的", pos: "adj" },
    { word: "dormant", meaning: "休眠的", pos: "adj" },
    { word: "jocular", meaning: "詼諧的", pos: "adj" },
    { word: "vertigo", meaning: "眩暈", pos: "n" },
    { word: "debunk", meaning: "揭穿 / 暴露", pos: "v" },
    { word: "malign", meaning: "誹謗", pos: "v" },
    { word: "torpid", meaning: "遲鈍的 / 懶散的", pos: "adj" },
    { word: "odium", meaning: "憎惡", pos: "n" },
    { word: "drab", meaning: "單調的", pos: "adj" }
  ],
  27: [
    { word: "embezzlement", meaning: "貪污 / 盜用", pos: "n" },
    { word: "concomitant", meaning: "伴隨的 / 同時發生的", pos: "adj" },
    { word: "aggrandize", meaning: "擴大 / 誇大", pos: "v" },
    { word: "extraneous", meaning: "無關的 / 外來的", pos: "adj" },
    { word: "pugnacious", meaning: "好鬥的 / 好戰的", pos: "adj" },
    { word: "burlesque", meaning: "滑稽戲", pos: "n" },
    { word: "hackneyed", meaning: "陳腐的", pos: "adj" },
    { word: "irascible", meaning: "易怒的", pos: "adj" },
    { word: "venerable", meaning: "值得尊敬的", pos: "adj" },
    { word: "cupidity", meaning: "貪婪 / 貪財", pos: "n" },
    { word: "obdurate", meaning: "頑固的 / 執拗的", pos: "adj" },
    { word: "sobriety", meaning: "清醒 / 莊重", pos: "n" },
    { word: "dwindle", meaning: "減少", pos: "v" },
    { word: "insular", meaning: "孤立的", pos: "adj" },
    { word: "vestige", meaning: "遺跡 / 殘餘", pos: "n" },
    { word: "dearth", meaning: "缺乏 / 稀少", pos: "n" },
    { word: "meager", meaning: "貧乏的", pos: "adj" },
    { word: "topple", meaning: "推翻", pos: "v" },
    { word: "offal", meaning: "內臟", pos: "n" },
    { word: "dour", meaning: "嚴厲的 / 陰沉的", pos: "adj" }
  ],
  28: [
    { word: "epistemology", meaning: "認識論", pos: "n" },
    { word: "compunction", meaning: "內疚 / 悔恨", pos: "n" },
    { word: "amalgamate", meaning: "合併 / 混合", pos: "v" },
    { word: "evanescent", meaning: "逐漸消失的 / 短暫的", pos: "adj" },
    { word: "quiescence", meaning: "靜止", pos: "n" },
    { word: "bombastic", meaning: "誇大的 / 言過其實的", pos: "adj" },
    { word: "heretical", meaning: "異端的", pos: "adj" },
    { word: "invidious", meaning: "招致不滿的 / 惹人反感的", pos: "adj" },
    { word: "veracious", meaning: "誠實的", pos: "adj" },
    { word: "culpable", meaning: "該責備的", pos: "adj" },
    { word: "oblation", meaning: "祭品", pos: "n" },
    { word: "sinister", meaning: "邪惡的", pos: "adj" },
    { word: "enchant", meaning: "使著迷", pos: "v" },
    { word: "insipid", meaning: "乏味的", pos: "adj" },
    { word: "wheedle", meaning: "哄騙", pos: "v" },
    { word: "dampen", meaning: "抑制 / 弄濕", pos: "v" },
    { word: "meddle", meaning: "干涉", pos: "v" },
    { word: "tirade", meaning: "長篇激烈的演說 / 抨擊", pos: "n" },
    { word: "paean", meaning: "讚美歌", pos: "n" },
    { word: "deft", meaning: "靈巧的", pos: "adj" }
  ],
  29: [
    { word: "equivocation", meaning: "模稜兩可的話", pos: "n" },
    { word: "complaisant", meaning: "殷勤的", pos: "adj" },
    { word: "amanuensis", meaning: "抄寫員 / 秘書", pos: "n" },
    { word: "equanimity", meaning: "平靜 / 鎮定", pos: "n" },
    { word: "recompense", meaning: "酬報", pos: "v" },
    { word: "bellicose", meaning: "好戰的 / 好鬥的", pos: "adj" },
    { word: "heterodox", meaning: "非正統的", pos: "adj" },
    { word: "invective", meaning: "謾罵 / 惡言", pos: "n" },
    { word: "veritable", meaning: "真正的", pos: "adj" },
    { word: "crockery", meaning: "陶器", pos: "n" },
    { word: "oblivion", meaning: "遺忘", pos: "n" },
    { word: "sedulous", meaning: "勤勉的", pos: "adj" },
    { word: "enthral", meaning: "使著迷", pos: "v" },
    { word: "impinge", meaning: "侵犯 / 撞擊", pos: "v" },
    { word: "winsome", meaning: "迷人的 / 惹人喜愛的", pos: "adj" },
    { word: "dabble", meaning: "涉獵", pos: "v" },
    { word: "mettle", meaning: "勇氣", pos: "n" },
    { word: "suborn", meaning: "收買", pos: "v" },
    { word: "pique", meaning: "激起", pos: "v" },
    { word: "clot", meaning: "凝塊", pos: "n" }
  ],
  30: [
    { word: "idiosyncrasy", meaning: "特質", pos: "n" },
    { word: "castigation", meaning: "嚴責 / 懲罰", pos: "n" },
    { word: "ambivalent", meaning: "矛盾的 / 猶豫不決的", pos: "adj" },
    { word: "epistolary", meaning: "書信的 / 書信體的", pos: "adj" },
    { word: "salubrious", meaning: "有益健康的 / 清爽的", pos: "adj" },
    { word: "axiomatic", meaning: "不證自明的 / 公理的", pos: "adj" },
    { word: "hyperbole", meaning: "誇張法", pos: "n" },
    { word: "insurgent", meaning: "叛亂者 / 起義者", pos: "n" },
    { word: "vindicate", meaning: "證明無罪", pos: "v" },
    { word: "corporal", meaning: "肉體的", pos: "adj" },
    { word: "opulence", meaning: "富裕", pos: "n" },
    { word: "sanguine", meaning: "樂觀的 / 紅潤的", pos: "adj" },
    { word: "epistle", meaning: "書信", pos: "n" },
    { word: "illicit", meaning: "非法的", pos: "adj" },
    { word: "abject", meaning: "卑劣的 / 淒慘的", pos: "adj" },
    { word: "crease", meaning: "摺痕", pos: "n" },
    { word: "morass", meaning: "沼澤 / 困境", pos: "n" },
    { word: "subdue", meaning: "征服", pos: "v" },
    { word: "pithy", meaning: "簡練的 / 精闢的", pos: "adj" },
    { word: "carp", meaning: "挑剔 / 吹毛求疵", pos: "v" }
  ],
  31: [
    { word: "improvidence", meaning: "揮霍", pos: "n" },
    { word: "camaraderie", meaning: "同志情誼 / 友情", pos: "n" },
    { word: "antithesis", meaning: "對立面 / 對照", pos: "n" },
    { word: "effrontery", meaning: "厚顏無恥", pos: "n" },
    { word: "scurrilous", meaning: "粗俗的 / 誹謗的", pos: "adj" },
    { word: "audacious", meaning: "大膽的 / 魯莽的", pos: "adj" },
    { word: "imbroglio", meaning: "錯綜複雜的局面 / 糾紛", pos: "n" },
    { word: "instigate", meaning: "煽動 / 唆使", pos: "v" },
    { word: "vitriolic", meaning: "尖酸刻薄的 / 惡意的", pos: "adj" },
    { word: "contrite", meaning: "悔罪的 / 痛悔的", pos: "adj" },
    { word: "oratorio", meaning: "神劇", pos: "n" },
    { word: "reticent", meaning: "沉默寡言的", pos: "adj" },
    { word: "epithet", meaning: "稱號", pos: "n" },
    { word: "holster", meaning: "手槍皮套", pos: "n" },
    { word: "abjure", meaning: "發誓放棄 / 公開放棄", pos: "v" },
    { word: "craven", meaning: "懦弱的 / 膽小的", pos: "adj" },
    { word: "morose", meaning: "鬱悶的", pos: "adj" },
    { word: "stolid", meaning: "遲鈍的 / 缺乏熱情的", pos: "adj" },
    { word: "posit", meaning: "假設", pos: "v" },
    { word: "cant", meaning: "斜坡", pos: "n" }
  ],
  32: [
    { word: "inauspicious", meaning: "不吉利的", pos: "adj" },
    { word: "approbation", meaning: "認可 / 贊許", pos: "n" },
    { word: "apocryphal", meaning: "偽造的 / 可疑的", pos: "adj" },
    { word: "dilettante", meaning: "業餘愛好者", pos: "n" },
    { word: "solicitous", meaning: "關切的 / 掛念的", pos: "adj" },
    { word: "attenuate", meaning: "變細 / 變弱", pos: "v" },
    { word: "immutable", meaning: "不變的", pos: "adj" },
    { word: "insinuate", meaning: "暗示", pos: "v" },
    { word: "voracious", meaning: "貪婪的", pos: "adj" },
    { word: "construe", meaning: "解釋 / 理解為", pos: "v" },
    { word: "ossified", meaning: "僵化的", pos: "adj" },
    { word: "reprieve", meaning: "緩刑 / 暫緩", pos: "n" },
    { word: "erratic", meaning: "反覆無常的", pos: "adj" },
    { word: "hapless", meaning: "倒霉的 / 不幸的", pos: "adj" },
    { word: "accede", meaning: "同意 / 答應", pos: "v" },
    { word: "covert", meaning: "秘密的", pos: "adj" },
    { word: "occult", meaning: "神秘的", pos: "adj" },
    { word: "sordid", meaning: "骯髒的", pos: "adj" },
    { word: "preen", meaning: "整理羽毛", pos: "v" },
    { word: "bung", meaning: "塞子", pos: "n" }
  ],
  33: [
    { word: "incorrigible", meaning: "積習難改的", pos: "adj" },
    { word: "anachronism", meaning: "時代錯誤 / 不合時宜的人事物", pos: "n" },
    { word: "apoplectic", meaning: "勃然大怒的", pos: "adj" },
    { word: "diaphanous", meaning: "透明的 / 精緻的", pos: "adj" },
    { word: "stigmatize", meaning: "侮辱", pos: "v" },
    { word: "assiduous", meaning: "勤奮的 / 專心致志的", pos: "adj" },
    { word: "impassive", meaning: "冷漠的", pos: "adj" },
    { word: "insidious", meaning: "潛伏的 / 陰險的", pos: "adj" },
    { word: "whimsical", meaning: "古怪的", pos: "adj" },
    { word: "confound", meaning: "使困惑", pos: "v" },
    { word: "palliate", meaning: "減輕 / 掩飾", pos: "v" },
    { word: "recourse", meaning: "求助", pos: "n" },
    { word: "erudite", meaning: "博學的", pos: "adj" },
    { word: "grumble", meaning: "抱怨", pos: "v" },
    { word: "accost", meaning: "搭訕 / 攀談", pos: "v" },
    { word: "cosset", meaning: "寵愛 / 溺愛", pos: "v" },
    { word: "odious", meaning: "可憎的", pos: "adj" },
    { word: "somber", meaning: "憂鬱的", pos: "adj" },
    { word: "quaff", meaning: "狂飲", pos: "v" },
    { word: "boor", meaning: "粗魯的人", pos: "n" }
  ],
  34: [
    { word: "inextricable", meaning: "無法擺脫的", pos: "adj" },
    { word: "vituperative", meaning: "辱罵的", pos: "adj" },
    { word: "apotheosis", meaning: "神化 / 典範 / 巔峰", pos: "n" },
    { word: "derivative", meaning: "衍生物 / 派生的", pos: "adj" },
    { word: "subsequent", meaning: "隨後的", pos: "adj" },
    { word: "aspersion", meaning: "誹謗 / 中傷", pos: "n" },
    { word: "imperious", meaning: "專橫的", pos: "adj" },
    { word: "insatiate", meaning: "貪得無厭的", pos: "adj" },
    { word: "abeyance", meaning: "中止 / 暫緩", pos: "n" },
    { word: "conflate", meaning: "合併", pos: "v" },
    { word: "parasite", meaning: "寄生蟲", pos: "n" },
    { word: "quixotic", meaning: "不切實際的 / 唐吉訶德式的", pos: "adj" },
    { word: "espouse", meaning: "支持 / 擁護", pos: "v" },
    { word: "grazing", meaning: "放牧", pos: "n" },
    { word: "acumen", meaning: "敏銳 / 聰明", pos: "n" },
    { word: "cogent", meaning: "有說服力的 / 令人信服的", pos: "adj" },
    { word: "opiate", meaning: "鴉片劑", pos: "n" },
    { word: "simper", meaning: "傻笑", pos: "v" },
    { word: "qualm", meaning: "疑慮", pos: "n" },
    { word: "bilk", meaning: "欺騙 / 詐騙", pos: "v" }
  ],
  35: [
    { word: "interlocutor", meaning: "對話者 / 談話對手", pos: "n" },
    { word: "tergiversate", meaning: "支吾其詞 / 變節、背叛", pos: "v" },
    { word: "archetypal", meaning: "原型的 / 典型的", pos: "adj" },
    { word: "dedication", meaning: "奉獻", pos: "n" },
    { word: "syncopated", meaning: "切分的", pos: "adj" },
    { word: "amorphous", meaning: "無定形的 / 雜亂的", pos: "adj" },
    { word: "impetuous", meaning: "衝動的 / 魯莽的", pos: "adj" },
    { word: "inoculate", meaning: "接種 / 灌輸", pos: "v" },
    { word: "abrogate", meaning: "廢除 / 取消", pos: "v" },
    { word: "churlish", meaning: "粗魯的 / 無禮的", pos: "adj" },
    { word: "partisan", meaning: "黨派的 / 偏袒的", pos: "n" },
    { word: "quisling", meaning: "賣國賊 / 內奸", pos: "n" },
    { word: "exigent", meaning: "緊急的 / 迫切的", pos: "adj" },
    { word: "ghastly", meaning: "可怕的", pos: "adj" },
    { word: "arcane", meaning: "神秘的 / 晦澀難懂的", pos: "adj" },
    { word: "clamor", meaning: "喧鬧 / 叫嚷", pos: "n" },
    { word: "orison", meaning: "祈禱", pos: "n" },
    { word: "shrill", meaning: "尖銳的", pos: "adj" },
    { word: "quash", meaning: "撤銷", pos: "v" },
    { word: "bane", meaning: "禍根 / 苦惱之源", pos: "n" }
  ],
  36: [
    { word: "intransigent", meaning: "不妥協的 / 固執的", pos: "adj" },
    { word: "recalcitrant", meaning: "桀驁不馴的 / 頑抗的", pos: "adj" },
    { word: "capitulate", meaning: "投降 / 屈服", pos: "v" },
    { word: "debilitate", meaning: "使衰弱", pos: "v" },
    { word: "tangential", meaning: "離題的 / 膚淺的", pos: "adj" },
    { word: "adumbrate", meaning: "預示 / 畫輪廓", pos: "v" },
    { word: "impromptu", meaning: "即席的", pos: "adj" },
    { word: "innocuous", meaning: "無害的", pos: "adj" },
    { word: "abstruse", meaning: "深奧的 / 難懂的", pos: "adj" },
    { word: "buttress", meaning: "扶壁 / 支撐", pos: "n" },
    { word: "pellucid", meaning: "清澈的 / 易懂的", pos: "adj" },
    { word: "quandary", meaning: "困境 / 窘境", pos: "n" },
    { word: "expiate", meaning: "贖罪 / 補償", pos: "v" },
    { word: "gainsay", meaning: "否認", pos: "v" },
    { word: "augury", meaning: "預兆 / 占卜", pos: "n" },
    { word: "chalet", meaning: "小木屋", pos: "n" },
    { word: "ornate", meaning: "華麗的", pos: "adj" },
    { word: "remiss", meaning: "怠忽職守的 / 疏忽的", pos: "adj" },
    { word: "skiff", meaning: "小船", pos: "n" },
    { word: "aver", meaning: "斷言 / 證實", pos: "v" }
  ],
  37: [
    { word: "multifarious", meaning: "多種多樣的 / 各式各樣的", pos: "adj" },
    { word: "ramification", meaning: "後果", pos: "n" },
    { word: "capricious", meaning: "反覆無常的 / 任性的", pos: "adj" },
    { word: "crustacean", meaning: "甲殼類", pos: "n" },
    { word: "transgress", meaning: "違反", pos: "v" },
    { word: "voluptuous", meaning: "撩人的", pos: "adj" },
    { word: "incidence", meaning: "發生率", pos: "n" },
    { word: "ingenuous", meaning: "天真的", pos: "adj" },
    { word: "admonish", meaning: "告誡 / 警告", pos: "v" },
    { word: "asperity", meaning: "嚴酷 / 粗魯 / 艱辛", pos: "adj" },
    { word: "penchant", meaning: "傾向 / 嗜好", pos: "n" },
    { word: "prurient", meaning: "好色的 / 淫慾的", pos: "adj" },
    { word: "expunge", meaning: "刪除 / 抹去", pos: "v" },
    { word: "furtive", meaning: "鬼鬼祟祟的", pos: "adj" },
    { word: "bereft", meaning: "喪失的 / 失去的", pos: "adj" },
    { word: "cavort", meaning: "歡躍 / 嬉戲", pos: "v" },
    { word: "padres", meaning: "神父", pos: "n" },
    { word: "recant", meaning: "撤回", pos: "v" },
    { word: "slack", meaning: "鬆弛的", pos: "adj" },
    { word: "usurp", meaning: "篡奪", pos: "v" }
  ],
  38: [
    { word: "obstetrician", meaning: "產科醫生", pos: "n" },
    { word: "predilection", meaning: "偏好 / 嗜好", pos: "n" },
    { word: "circumvent", meaning: "規避 / 繞過", pos: "v" },
    { word: "corpulence", meaning: "肥胖 / 臃腫", pos: "n" },
    { word: "truculence", meaning: "好鬥", pos: "n" },
    { word: "volubility", meaning: "流利", pos: "n" },
    { word: "incipient", meaning: "初期的", pos: "adj" },
    { word: "ineffable", meaning: "言語難以表達的", pos: "adj" },
    { word: "affluent", meaning: "富裕的 / 豐富的", pos: "adj" },
    { word: "arrogate", meaning: "冒稱 / 僭取", pos: "v" },
    { word: "petulant", meaning: "暴躁的", pos: "adj" },
    { word: "prodigal", meaning: "揮霍的", pos: "adj" },
    { word: "faddish", meaning: "趨於時尚的", pos: "adj" },
    { word: "foppish", meaning: "紈絝子弟的", pos: "adj" },
    { word: "blithe", meaning: "快樂無憂的", pos: "adj" },
    { word: "caucus", meaning: "核心會議 / 幹部會議", pos: "n" },
    { word: "pallid", meaning: "蒼白的 / 暗淡的", pos: "adj" },
    { word: "quaint", meaning: "古雅的 / 奇特的", pos: "adj" },
    { word: "staid", meaning: "沉著的 / 穩重的", pos: "adj" },
    { word: "trite", meaning: "陳腐的 / 平庸的", pos: "adj" }
  ],
  39: [
    { word: "obstreperous", meaning: "喧鬧的 / 難駕馭的", pos: "adj" },
    { word: "pertinacious", meaning: "頑固的 / 執拗的", pos: "adj" },
    { word: "compendium", meaning: "摘要 / 概略", pos: "n" },
    { word: "convoluted", meaning: "費解的", pos: "adj" },
    { word: "vaticinate", meaning: "預言", pos: "v" },
    { word: "vociferous", meaning: "喧嘩的 / 大聲叫嚷的", pos: "adj" },
    { word: "incumbent", meaning: "義不容辭的 / 現任的", pos: "adj" },
    { word: "indignant", meaning: "憤慨的", pos: "adj" },
    { word: "alacrity", meaning: "敏捷 / 樂意", pos: "n" },
    { word: "arboreal", meaning: "樹木的 / 棲息在樹上的", pos: "adj" },
    { word: "preamble", meaning: "序言", pos: "n" },
    { word: "pristine", meaning: "原始的", pos: "adj" },
    { word: "fallacy", meaning: "謬誤", pos: "n" },
    { word: "finicky", meaning: "過分講究的", pos: "adj" },
    { word: "bodkin", meaning: "錐子", pos: "n" },
    { word: "captor", meaning: "捕獲者", pos: "n" },
    { word: "pariah", meaning: "賤民 / 被社會遺棄者", pos: "n" },
    { word: "pucker", meaning: "起皺", pos: "v" },
    { word: "stoop", meaning: "屈身", pos: "v" },
    { word: "toady", meaning: "諂媚者 / 拍馬屁的人", pos: "n" }
  ],
  40: [
    { word: "onomatopoeia", meaning: "擬聲詞", pos: "n" },
    { word: "ostentatious", meaning: "炫耀的", pos: "adj" },
    { word: "condescend", meaning: "屈尊", pos: "v" },
    { word: "confluence", meaning: "匯流 / 聚集", pos: "n" },
    { word: "vindictive", meaning: "報復性的", pos: "adj" },
    { word: "vituperate", meaning: "謾罵 / 責罵", pos: "v" },
    { word: "incursion", meaning: "入侵", pos: "n" },
    { word: "indelible", meaning: "難以磨滅的", pos: "adj" },
    { word: "amenable", meaning: "順從的 / 願意接受的", pos: "adj" },
    { word: "anathema", meaning: "詛咒 / 令人討厭的事物", pos: "n" },
    { word: "precious", meaning: "珍貴的", pos: "adj" },
    { word: "preclude", meaning: "排除 / 阻止", pos: "v" },
    { word: "fatuous", meaning: "愚笨的 / 昏庸的", pos: "adj" },
    { word: "fervent", meaning: "熱烈的", pos: "adj" },
    { word: "cajole", meaning: "哄騙 / 誘騙", pos: "v" },
    { word: "candor", meaning: "坦白 / 直率", pos: "n" },
    { word: "pebble", meaning: "小卵石", pos: "n" },
    { word: "penury", meaning: "赤貧", pos: "n" },
    { word: "strut", meaning: "趾高氣揚地走", pos: "v" },
    { word: "tepid", meaning: "微溫的", pos: "adj" }
  ]
};

export function getWordSet(round: number): Word[] {
  // If we run out of sets, loop back
  const setKeys = Object.keys(wordSets).map(Number).sort((a, b) => a - b);
  const maxSet = setKeys[setKeys.length - 1];
  const actualRound = ((round - 1) % maxSet) + 1;
  return wordSets[actualRound];
}
